In [6]:
import pandas as pd
from dotenv import load_dotenv
import os
from datetime import date, timedelta
import time
import json
import ijson
from sqlalchemy import create_engine
from tqdm import tqdm

In [7]:
import sys
sys.path.append('./lib')

import library_st_data_processing as lsdp

In [8]:
# load .env from the current directory (or specify a path)
load_dotenv(dotenv_path=".env")
api_key = os.getenv("ST_API_KEY")

In [9]:
base_url = 'https://api.sensortower.com'

In [10]:
today_str = date.today().strftime("%Y-%m-%d")
timestamp = int(time.time())

# Base Layer

**Get Raw File: Top Game Annual Performance**

In [5]:
# Manual Download

**Get Raw File: Game Full Info**

In [8]:
# Load Top Game Annual Performance file
df_top_game_annual_performance = pd.read_csv("data/base/st_webdownload_annual_game_performance_2025-10-23.csv")

In [10]:
# Get the unified_app_ids
unified_app_ids = set(list(df_top_game_annual_performance["Unified ID"]))

In [18]:
# Retrieve Game Full Info file
df_game_full_info = lsdp.retrieve_full_info_game_table(api_key, base_url, unified_app_ids)

Get canonical app data...
making call for chunk number 1
call successful!
making call for chunk number 2
call successful!
making call for chunk number 3
call successful!
making call for chunk number 4
call successful!
making call for chunk number 5
call successful!
making call for chunk number 6
call successful!
making call for chunk number 7
call successful!
making call for chunk number 8
call successful!
making call for chunk number 9
call successful!
making call for chunk number 10
call successful!
making call for chunk number 11
call successful!
making call for chunk number 12
call successful!
making call for chunk number 13
call successful!
making call for chunk number 14
call successful!
making call for chunk number 15
call successful!
making call for chunk number 16
call successful!
making call for chunk number 17
call successful!
making call for chunk number 18
call successful!
making call for chunk number 19
call successful!
making call for chunk number 20
call successful!
making call for chunk number 21
call successful!
making call for chunk number 22
call successful!
making call for chunk number 23
call successful!
making call for chunk number 24
call successful!
making call for chunk number 25
call successful!
making call for chunk number 26
call successful!
making call for chunk number 27
call successful!
making call for chunk number 28
call successful!
making call for chunk number 29
call successful!
making call for chunk number 30
call successful!
making call for chunk number 31
call successful!
making call for chunk number 32
call successful!
making call for chunk number 33
call successful!
making call for chunk number 34
call successful!
making call for chunk number 35
call successful!
making call for chunk number 36
call successful!
making call for chunk number 37
call successful!
making call for chunk number 38
call successful!
making call for chunk number 39
call successful!
making call for chunk number 40
call successful!
making call for chunk number 41
call successful!
making call for chunk number 42
call successful!
making call for chunk number 43
call successful!
making call for chunk number 44
call successful!
making call for chunk number 45
call successful!
making call for chunk number 46
call successful!
making call for chunk number 47
call successful!
making call for chunk number 48
call successful!
making call for chunk number 49
call successful!
making call for chunk number 50
call successful!
making call for chunk number 51
call successful!
making call for chunk number 52
call successful!
making call for chunk number 53
call successful!
making call for chunk number 54
call successful!
making call for chunk number 55
call successful!
making call for chunk number 56
call successful!
making call for chunk number 57
call successful!
making call for chunk number 58
call successful!
making call for chunk number 59
call successful!
making call for chunk number 60
call successful!
making call for chunk number 61
call successful!
making call for chunk number 62
call successful!
making call for chunk number 63
call successful!
making call for chunk number 64
call successful!
making call for chunk number 65
call successful!
making call for chunk number 66
call successful!
making call for chunk number 67
call successful!
making call for chunk number 68
call successful!
making call for chunk number 69
call successful!
making call for chunk number 70
call successful!
making call for chunk number 71
call successful!
making call for chunk number 72
call successful!
making call for chunk number 73
call successful!
making call for chunk number 74
call successful!
making call for chunk number 75
call successful!
making call for chunk number 76
call successful!
making call for chunk number 77
call successful!
making call for chunk number 78
call successful!
making call for chunk number 79
call successful!
making call for chunk number 80
call successful!
making call for chunk number 81
call successful!
making call for chunk number 82
call successful!
making call for chunk number 83
call successful!
making call for chunk number 84
call successful!
making call for chunk number 85
call successful!
making call for chunk number 86
call successful!
making call for chunk number 87
call successful!
making call for chunk number 88
call successful!
making call for chunk number 89
call successful!
making call for chunk number 90
call successful!
making call for chunk number 91
call successful!
making call for chunk number 92
call successful!
making call for chunk number 93
call successful!
making call for chunk number 94
call successful!
making call for chunk number 95
call successful!
making call for chunk number 96
call successful!
making call for chunk number 97
call successful!
making call for chunk number 98
call successful!
making call for chunk number 99
call successful!
making call for chunk number 100
call successful!
making call for chunk number 101
call successful!
making call for chunk number 102
call successful!
making call for chunk number 103
call successful!
making call for chunk number 104
call successful!
making call for chunk number 105
call successful!
making call for chunk number 106
call successful!
making call for chunk number 107
call successful!
making call for chunk number 108
call successful!
making call for chunk number 109
call successful!
making call for chunk number 110
call successful!
making call for chunk number 111
call successful!
making call for chunk number 112
call successful!
making call for chunk number 113
call successful!
making call for chunk number 114
call successful!
making call for chunk number 115
call successful!
making call for chunk number 116
call successful!
making call for chunk number 117
call successful!
making call for chunk number 118
call successful!
making call for chunk number 119
call successful!
making call for chunk number 120
call successful!
making call for chunk number 121
call successful!
making call for chunk number 122
call successful!
making call for chunk number 123
call successful!
making call for chunk number 124
call successful!
making call for chunk number 125
call successful!
making call for chunk number 126
call successful!
making call for chunk number 127
call successful!
making call for chunk number 128
call successful!
making call for chunk number 129
call successful!
making call for chunk number 130
call successful!
making call for chunk number 131
call successful!
making call for chunk number 132
call successful!
making call for chunk number 133
call successful!
making call for chunk number 134
call successful!
making call for chunk number 135
call successful!
making call for chunk number 136
call successful!
making call for chunk number 137
call successful!
making call for chunk number 138
call successful!
making call for chunk number 139
call successful!
making call for chunk number 140
call successful!
making call for chunk number 141
call successful!
making call for chunk number 142
call successful!
making call for chunk number 143
call successful!
making call for chunk number 144
call successful!
making call for chunk number 145
call successful!
making call for chunk number 146
call successful!
making call for chunk number 147
call successful!
making call for chunk number 148
call successful!
making call for chunk number 149
call successful!
making call for chunk number 150
call successful!
making call for chunk number 151
call successful!
making call for chunk number 152
call successful!
making call for chunk number 153
call successful!
making call for chunk number 154
call successful!
making call for chunk number 155
call successful!
making call for chunk number 156
call successful!
making call for chunk number 157
call successful!
making call for chunk number 158
call successful!
making call for chunk number 159
call successful!
making call for chunk number 160
call successful!
making call for chunk number 161
call successful!
making call for chunk number 162
call successful!
making call for chunk number 163
call successful!
making call for chunk number 164
call successful!
making call for chunk number 165
call successful!
making call for chunk number 166
call successful!
making call for chunk number 167
call successful!
making call for chunk number 168
call successful!
making call for chunk number 169
call successful!
making call for chunk number 170
call successful!
making call for chunk number 171
call successful!
making call for chunk number 172
call successful!
making call for chunk number 173
call successful!
making call for chunk number 174
call successful!
making call for chunk number 175
call successful!
making call for chunk number 176
call successful!
making call for chunk number 177
call successful!
making call for chunk number 178
call successful!
making call for chunk number 179
call successful!
making call for chunk number 180
call successful!
making call for chunk number 181
call successful!
making call for chunk number 182
call successful!
making call for chunk number 183
call successful!
making call for chunk number 184
call successful!
making call for chunk number 185
call successful!
making call for chunk number 186
call successful!
making call for chunk number 187
call successful!
making call for chunk number 188
call successful!
making call for chunk number 189
call successful!
making call for chunk number 190
call successful!
making call for chunk number 191
call successful!
making call for chunk number 192
call successful!
making call for chunk number 193
call successful!
making call for chunk number 194
call successful!
making call for chunk number 195
call successful!
making call for chunk number 196
call successful!
making call for chunk number 197
call successful!
making call for chunk number 198
call successful!
making call for chunk number 199
call successful!
making call for chunk number 200
call successful!
making call for chunk number 201
call successful!
making call for chunk number 202
call successful!
making call for chunk number 203
call successful!
making call for chunk number 204
call successful!
making call for chunk number 205
call successful!
making call for chunk number 206
call successful!
making call for chunk number 207
call successful!
making call for chunk number 208
call successful!
making call for chunk number 209
call successful!
making call for chunk number 210
call successful!
making call for chunk number 211
call successful!
making call for chunk number 212
call successful!
making call for chunk number 213
call successful!
making call for chunk number 214
call successful!
making call for chunk number 215
call successful!
making call for chunk number 216
call successful!
making call for chunk number 217
call successful!
making call for chunk number 218
call successful!
making call for chunk number 219
call successful!
making call for chunk number 220
call successful!
making call for chunk number 221
call successful!
making call for chunk number 222
call successful!
making call for chunk number 223
call successful!
making call for chunk number 224
call successful!
making call for chunk number 225
call successful!
making call for chunk number 226
call successful!
making call for chunk number 227
call successful!
making call for chunk number 228
call successful!
making call for chunk number 229
call successful!
making call for chunk number 230
call successful!
making call for chunk number 231
call successful!
making call for chunk number 232
call successful!
making call for chunk number 233
call successful!
making call for chunk number 234
call successful!
making call for chunk number 235
call successful!
making call for chunk number 236
call successful!
making call for chunk number 237
call successful!
making call for chunk number 238
call successful!
making call for chunk number 239
call successful!
making call for chunk number 240
call successful!
making call for chunk number 241
call successful!
making call for chunk number 242
call successful!
making call for chunk number 243
call successful!
making call for chunk number 244
call successful!
making call for chunk number 245
call successful!
making call for chunk number 246
call successful!
making call for chunk number 247
call successful!
making call for chunk number 248
call successful!
making call for chunk number 249
call successful!
making call for chunk number 250
call successful!
making call for chunk number 251
call successful!
making call for chunk number 252
call successful!
making call for chunk number 253
call successful!
making call for chunk number 254
call successful!
making call for chunk number 255
call successful!
making call for chunk number 256
call successful!
making call for chunk number 257
call successful!
making call for chunk number 258
call successful!
making call for chunk number 259
call successful!
making call for chunk number 260
call successful!
making call for chunk number 261
call successful!
making call for chunk number 262
call successful!
making call for chunk number 263
call successful!
making call for chunk number 264
call successful!
making call for chunk number 265
call successful!
making call for chunk number 266
call successful!
making call for chunk number 267
call successful!
making call for chunk number 268
call successful!
making call for chunk number 269
call successful!
making call for chunk number 270
call successful!
making call for chunk number 271
call successful!
making call for chunk number 272
call successful!
making call for chunk number 273
call successful!
making call for chunk number 274
call successful!
making call for chunk number 275
call successful!
making call for chunk number 276
call successful!
making call for chunk number 277
call successful!
making call for chunk number 278
call successful!
making call for chunk number 279
call successful!
making call for chunk number 280
call successful!
making call for chunk number 281
call successful!
making call for chunk number 282
call successful!
making call for chunk number 283
call successful!
making call for chunk number 284
call successful!
making call for chunk number 285
call successful!
making call for chunk number 286
call successful!
making call for chunk number 287
call successful!
making call for chunk number 288
call successful!
making call for chunk number 289
call successful!
making call for chunk number 290
call successful!
making call for chunk number 291
call successful!
making call for chunk number 292
call successful!
making call for chunk number 293
call successful!
making call for chunk number 294
call successful!
making call for chunk number 295
call successful!
making call for chunk number 296
call successful!
making call for chunk number 297
call successful!
making call for chunk number 298
call successful!
making call for chunk number 299
call successful!
making call for chunk number 300
call successful!
making call for chunk number 301
call successful!
making call for chunk number 302
call successful!
making call for chunk number 303
call successful!
making call for chunk number 304
call successful!
making call for chunk number 305
call successful!
making call for chunk number 306
call successful!
making call for chunk number 307
call successful!
making call for chunk number 308
call successful!
making call for chunk number 309
call successful!
making call for chunk number 310
call successful!
making call for chunk number 311
call successful!
making call for chunk number 312
call successful!
making call for chunk number 313
call successful!
making call for chunk number 314
call successful!
making call for chunk number 315
call successful!
making call for chunk number 316
call successful!
making call for chunk number 317
call successful!
making call for chunk number 318
call successful!
making call for chunk number 319
call successful!
making call for chunk number 320
call successful!
making call for chunk number 321
call successful!
making call for chunk number 322
call successful!
making call for chunk number 323
call successful!
making call for chunk number 324
call successful!
making call for chunk number 325
call successful!
making call for chunk number 326
call successful!
making call for chunk number 327
call successful!
making call for chunk number 328
call successful!
making call for chunk number 329
call successful!
making call for chunk number 330
call successful!
making call for chunk number 331
call successful!
making call for chunk number 332
call successful!
making call for chunk number 333
call successful!
making call for chunk number 334
call successful!
making call for chunk number 335
call successful!
making call for chunk number 336
call successful!
making call for chunk number 337
call successful!
making call for chunk number 338
call successful!
making call for chunk number 339
call successful!
making call for chunk number 340
call successful!
making call for chunk number 341
call successful!
making call for chunk number 342
call successful!
making call for chunk number 343
call successful!
making call for chunk number 344
call successful!
making call for chunk number 345
call successful!
making call for chunk number 346
call successful!
making call for chunk number 347
call successful!
making call for chunk number 348
call successful!
making call for chunk number 349
call successful!
making call for chunk number 350
call successful!
making call for chunk number 351
call successful!
making call for chunk number 352
call successful!
making call for chunk number 353
call successful!
making call for chunk number 354
call successful!
making call for chunk number 355
call successful!
making call for chunk number 356
call successful!
making call for chunk number 357
call successful!
making call for chunk number 358
call successful!
making call for chunk number 359
call successful!
making call for chunk number 360
call successful!
making call for chunk number 361
call successful!
making call for chunk number 362
call successful!
making call for chunk number 363
call successful!
making call for chunk number 364
call successful!
making call for chunk number 365
call successful!
making call for chunk number 366
call successful!
making call for chunk number 367
call successful!
making call for chunk number 368
call successful!
making call for chunk number 369
call successful!
making call for chunk number 370
call successful!
making call for chunk number 371
call successful!
making call for chunk number 372
call successful!
making call for chunk number 373
call successful!
making call for chunk number 374
call successful!
making call for chunk number 375
call successful!
making call for chunk number 376
call successful!
making call for chunk number 377
call successful!
making call for chunk number 378
call successful!
making call for chunk number 379
call successful!
making call for chunk number 380
call successful!
making call for chunk number 381
call successful!
making call for chunk number 382
call successful!
making call for chunk number 383
call successful!
making call for chunk number 384
call successful!
making call for chunk number 385
call successful!
making call for chunk number 386
call successful!
making call for chunk number 387
call successful!
making call for chunk number 388
call successful!
making call for chunk number 389
call successful!
making call for chunk number 390
call successful!
making call for chunk number 391
call successful!
making call for chunk number 392
call successful!
making call for chunk number 393
call successful!
making call for chunk number 394
call successful!
making call for chunk number 395
call successful!
making call for chunk number 396
call successful!
making call for chunk number 397
call successful!
making call for chunk number 398
call successful!
making call for chunk number 399
call successful!
making call for chunk number 400
call successful!
making call for chunk number 401
call successful!

In [19]:
# Export the file to csv and save to base layer folder
df_game_full_info.to_csv('data/base/st_api_game_full_info_{}.csv'.format(timestamp), index=False)

**Get Raw File: App Full Info**

In [6]:
# Read file Game Full Info
df_game_full_info = pd.read_csv('data/base/st_api_game_full_info_2025-10-23.csv')

In [8]:
# Retrieve file App Full Info
df_app_full_info = lsdp.get_local_app_info_from_game_full_info_table(api_key, base_url, df_game_full_info)

Extracting app list from game table...
Getting iOS apps info...
making call for chunk number 1
call successful!
making call for chunk number 2
call successful!
making call for chunk number 3
call successful!
making call for chunk number 4
call successful!
making call for chunk number 5
call successful!
making call for chunk number 6
call successful!
making call for chunk number 7
call successful!
making call for chunk number 8
call successful!
making call for chunk number 9
call successful!
making call for chunk number 10
call successful!
making call for chunk number 11
call successful!
making call for chunk number 12
call successful!
making call for chunk number 13
call successful!
making call for chunk number 14
call successful!
making call for chunk number 15
call successful!
making call for chunk number 16
call successful!
making call for chunk number 17
call successful!
making call for chunk number 18
call successful!
making call for chunk number 19
call successful!
making call for chunk number 20
call successful!
making call for chunk number 21
call successful!
making call for chunk number 22
call successful!
making call for chunk number 23
call successful!
making call for chunk number 24
call successful!
making call for chunk number 25
call successful!
making call for chunk number 26
call successful!
making call for chunk number 27
call successful!
making call for chunk number 28
call successful!
making call for chunk number 29
call successful!
making call for chunk number 30
call successful!
making call for chunk number 31
call successful!
making call for chunk number 32
call successful!
making call for chunk number 33
call successful!
making call for chunk number 34
call successful!
making call for chunk number 35
call successful!
making call for chunk number 36
call successful!
making call for chunk number 37
call successful!
making call for chunk number 38
call successful!
making call for chunk number 39
call successful!
making call for chunk number 40
call successful!
making call for chunk number 41
call successful!
making call for chunk number 42
call successful!
making call for chunk number 43
call successful!
making call for chunk number 44
call successful!
making call for chunk number 45
call successful!
making call for chunk number 46
call successful!
making call for chunk number 47
call successful!
making call for chunk number 48
call successful!
making call for chunk number 49
call successful!
making call for chunk number 50
call successful!
making call for chunk number 51
call successful!
making call for chunk number 52
call successful!
making call for chunk number 53
call successful!
making call for chunk number 54
call successful!
making call for chunk number 55
call successful!
making call for chunk number 56
call successful!
making call for chunk number 57
call successful!
making call for chunk number 58
call successful!
making call for chunk number 59
call successful!
making call for chunk number 60
call successful!
making call for chunk number 61
call successful!
making call for chunk number 62
call successful!
making call for chunk number 63
call successful!
making call for chunk number 64
call successful!
making call for chunk number 65
call successful!
making call for chunk number 66
call successful!
making call for chunk number 67
call successful!
making call for chunk number 68
call successful!
making call for chunk number 69
call successful!
making call for chunk number 70
call successful!
making call for chunk number 71
call successful!
making call for chunk number 72
call successful!
making call for chunk number 73
call successful!
making call for chunk number 74
call successful!
making call for chunk number 75
call successful!
making call for chunk number 76
call successful!
making call for chunk number 77
call successful!
making call for chunk number 78
call successful!
making call for chunk number 79
call successful!
making call for chunk number 80
call successful!
making call for chunk number 81
call successful!
making call for chunk number 82
call successful!
making call for chunk number 83
call successful!
making call for chunk number 84
call successful!
making call for chunk number 85
call successful!
making call for chunk number 86
call successful!
making call for chunk number 87
call successful!
making call for chunk number 88
call successful!
making call for chunk number 89
call successful!
making call for chunk number 90
call successful!
making call for chunk number 91
call successful!
making call for chunk number 92
call successful!
making call for chunk number 93
call successful!
making call for chunk number 94
call successful!
making call for chunk number 95
call successful!
making call for chunk number 96
call successful!
making call for chunk number 97
call successful!
making call for chunk number 98
call successful!
making call for chunk number 99
call successful!
making call for chunk number 100
call successful!
making call for chunk number 101
call successful!
making call for chunk number 102
call successful!
making call for chunk number 103
call successful!
making call for chunk number 104
call successful!
making call for chunk number 105
call successful!
making call for chunk number 106
call successful!
making call for chunk number 107
call successful!
making call for chunk number 108
call successful!
making call for chunk number 109
call successful!
making call for chunk number 110
call successful!
making call for chunk number 111
call successful!
making call for chunk number 112
call successful!
making call for chunk number 113
call successful!
making call for chunk number 114
call successful!
making call for chunk number 115
call successful!
making call for chunk number 116
call successful!
making call for chunk number 117
call successful!
making call for chunk number 118
call successful!
making call for chunk number 119
call successful!
making call for chunk number 120
call successful!
making call for chunk number 121
call successful!
making call for chunk number 122
call successful!
making call for chunk number 123
call successful!
making call for chunk number 124
call successful!
making call for chunk number 125
call successful!
making call for chunk number 126
call successful!
making call for chunk number 127
call successful!
making call for chunk number 128
call successful!
making call for chunk number 129
call successful!
making call for chunk number 130
call successful!
making call for chunk number 131
call successful!
making call for chunk number 132
call successful!
making call for chunk number 133
call successful!
making call for chunk number 134
call successful!
making call for chunk number 135
call successful!
making call for chunk number 136
call successful!
making call for chunk number 137
call successful!
making call for chunk number 138
call successful!
making call for chunk number 139
call successful!
making call for chunk number 140
call successful!
making call for chunk number 141
call successful!
making call for chunk number 142
call successful!
making call for chunk number 143
call successful!
making call for chunk number 144
call successful!
making call for chunk number 145
call successful!
making call for chunk number 146
call successful!
making call for chunk number 147
call successful!
making call for chunk number 148
call successful!
making call for chunk number 149
call successful!
making call for chunk number 150
call successful!
making call for chunk number 151
call successful!
making call for chunk number 152
call successful!
making call for chunk number 153
call successful!
making call for chunk number 154
call successful!
making call for chunk number 155
call successful!
making call for chunk number 156
call successful!
making call for chunk number 157
call successful!
making call for chunk number 158
call successful!
making call for chunk number 159
call successful!
making call for chunk number 160
call successful!
making call for chunk number 161
call successful!
making call for chunk number 162
call successful!
making call for chunk number 163
call successful!
making call for chunk number 164
call successful!
making call for chunk number 165
call successful!
making call for chunk number 166
call successful!
making call for chunk number 167
call successful!
making call for chunk number 168
call successful!
making call for chunk number 169
call successful!
making call for chunk number 170
call successful!
making call for chunk number 171
call successful!
making call for chunk number 172
call successful!
making call for chunk number 173
call successful!
making call for chunk number 174
call successful!
making call for chunk number 175
call successful!
making call for chunk number 176
call successful!
making call for chunk number 177
call successful!
making call for chunk number 178
call successful!
making call for chunk number 179
call successful!
making call for chunk number 180
call successful!
making call for chunk number 181
call successful!
making call for chunk number 182
call successful!
making call for chunk number 183
call successful!
making call for chunk number 184
call successful!
making call for chunk number 185
call successful!
making call for chunk number 186
call successful!
making call for chunk number 187
call successful!
making call for chunk number 188
call successful!
making call for chunk number 189
call successful!
making call for chunk number 190
call successful!
making call for chunk number 191
call successful!
making call for chunk number 192
call successful!
making call for chunk number 193
call successful!
making call for chunk number 194
call successful!
making call for chunk number 195
call successful!
making call for chunk number 196
call successful!
making call for chunk number 197
call successful!
making call for chunk number 198
call successful!
making call for chunk number 199
call successful!
making call for chunk number 200
call successful!
making call for chunk number 201
call successful!
making call for chunk number 202
call successful!
making call for chunk number 203
call successful!
making call for chunk number 204
call successful!
making call for chunk number 205
call successful!
making call for chunk number 206
call successful!
making call for chunk number 207
call successful!
making call for chunk number 208
call successful!
making call for chunk number 209
call successful!
making call for chunk number 210
call successful!
making call for chunk number 211
call successful!
making call for chunk number 212
call successful!
making call for chunk number 213
call successful!
making call for chunk number 214
call successful!
making call for chunk number 215
call successful!
making call for chunk number 216
call successful!
making call for chunk number 217
call successful!
making call for chunk number 218
call successful!
making call for chunk number 219
call successful!
making call for chunk number 220
call successful!
making call for chunk number 221
call successful!
making call for chunk number 222
call successful!
making call for chunk number 223
call successful!
making call for chunk number 224
call successful!
making call for chunk number 225
call successful!
making call for chunk number 226
call successful!
making call for chunk number 227
call successful!
making call for chunk number 228
call successful!
making call for chunk number 229
call successful!
making call for chunk number 230
call successful!
making call for chunk number 231
call successful!
making call for chunk number 232
call successful!
making call for chunk number 233
call successful!
making call for chunk number 234
call successful!
making call for chunk number 235
call successful!
making call for chunk number 236
call successful!
making call for chunk number 237
call successful!
making call for chunk number 238
call successful!
making call for chunk number 239
call successful!
making call for chunk number 240
call successful!
making call for chunk number 241
call successful!
making call for chunk number 242
call successful!
making call for chunk number 243
call successful!
making call for chunk number 244
call successful!
making call for chunk number 245
call successful!
making call for chunk number 246
call successful!
making call for chunk number 247
call successful!
making call for chunk number 248
call successful!
making call for chunk number 249
call successful!
making call for chunk number 250
call successful!
making call for chunk number 251
call successful!
making call for chunk number 252
call successful!
making call for chunk number 253
call successful!
making call for chunk number 254
call successful!
making call for chunk number 255
call successful!
making call for chunk number 256
call successful!
making call for chunk number 257
call successful!
making call for chunk number 258
call successful!
making call for chunk number 259
call successful!
making call for chunk number 260
call successful!
making call for chunk number 261
call successful!
making call for chunk number 262
call successful!
making call for chunk number 263
call successful!
making call for chunk number 264
call successful!
making call for chunk number 265
call successful!
making call for chunk number 266
call successful!
making call for chunk number 267
call successful!
making call for chunk number 268
call successful!
making call for chunk number 269
call successful!
making call for chunk number 270
call successful!
making call for chunk number 271
call successful!
making call for chunk number 272
call successful!
making call for chunk number 273
call successful!
making call for chunk number 274
call successful!
making call for chunk number 275
call successful!
making call for chunk number 276
call successful!
making call for chunk number 277
call successful!
making call for chunk number 278
call successful!
making call for chunk number 279
call successful!
making call for chunk number 280
call successful!
making call for chunk number 281
call successful!
making call for chunk number 282
call successful!
making call for chunk number 283
call successful!
making call for chunk number 284
call successful!
making call for chunk number 285
call successful!
making call for chunk number 286
call successful!
making call for chunk number 287
call successful!
making call for chunk number 288
call successful!
making call for chunk number 289
call successful!
making call for chunk number 290
call successful!
making call for chunk number 291
call successful!
making call for chunk number 292
call successful!
making call for chunk number 293
call successful!
making call for chunk number 294
call successful!
making call for chunk number 295
call successful!
making call for chunk number 296
call successful!
making call for chunk number 297
call successful!
making call for chunk number 298
call successful!
making call for chunk number 299
call successful!
making call for chunk number 300
call successful!
making call for chunk number 301
call successful!
making call for chunk number 302
call successful!
making call for chunk number 303
call successful!
making call for chunk number 304
call successful!
making call for chunk number 305
call successful!
making call for chunk number 306
call successful!
making call for chunk number 307
call successful!
making call for chunk number 308
call successful!
making call for chunk number 309
call successful!
making call for chunk number 310
call successful!
making call for chunk number 311
call successful!
making call for chunk number 312
call successful!
making call for chunk number 313
call successful!
making call for chunk number 314
call successful!
making call for chunk number 315
call successful!
making call for chunk number 316
call successful!
making call for chunk number 317
call successful!
making call for chunk number 318
call successful!
making call for chunk number 319
call successful!
making call for chunk number 320
call successful!
making call for chunk number 321
call successful!
making call for chunk number 322
call successful!
making call for chunk number 323
call successful!
making call for chunk number 324
call successful!
making call for chunk number 325
call successful!
making call for chunk number 326
call successful!
making call for chunk number 327
call successful!
making call for chunk number 328
call successful!
making call for chunk number 329
call successful!
making call for chunk number 330
call successful!
making call for chunk number 331
call successful!
making call for chunk number 332
call successful!
making call for chunk number 333
call successful!
making call for chunk number 334
call successful!
making call for chunk number 335
call successful!
making call for chunk number 336
call successful!
making call for chunk number 337
call successful!
making call for chunk number 338
call successful!
making call for chunk number 339
call successful!
making call for chunk number 340
call successful!
making call for chunk number 341
call successful!
making call for chunk number 342
call successful!
making call for chunk number 343
call successful!
making call for chunk number 344
call successful!
making call for chunk number 345
call successful!
making call for chunk number 346
call successful!
making call for chunk number 347
call successful!
making call for chunk number 348
call successful!
making call for chunk number 349
call successful!
making call for chunk number 350
call successful!
making call for chunk number 351
call successful!
making call for chunk number 352
call successful!
making call for chunk number 353
call successful!
making call for chunk number 354
call successful!
making call for chunk number 355
call successful!
making call for chunk number 356
call successful!
making call for chunk number 357
call successful!
making call for chunk number 358
call successful!
making call for chunk number 359
call successful!
making call for chunk number 360
call successful!
making call for chunk number 361
call successful!
making call for chunk number 362
call successful!
making call for chunk number 363
call successful!
making call for chunk number 364
call successful!
making call for chunk number 365
call successful!
making call for chunk number 366
call successful!
making call for chunk number 367
call successful!
making call for chunk number 368
call successful!
making call for chunk number 369
call successful!
making call for chunk number 370
call successful!
making call for chunk number 371
call successful!
making call for chunk number 372
call successful!
making call for chunk number 373
call successful!
making call for chunk number 374
call successful!
making call for chunk number 375
call successful!
making call for chunk number 376
call successful!
making call for chunk number 377
call successful!
making call for chunk number 378
call successful!
making call for chunk number 379
call successful!
making call for chunk number 380
call successful!
making call for chunk number 381
call successful!
making call for chunk number 382
call successful!
making call for chunk number 383
call successful!
making call for chunk number 384
call successful!
making call for chunk number 385
call successful!
making call for chunk number 386
call successful!
making call for chunk number 387
call successful!
making call for chunk number 388
call successful!
making call for chunk number 389
call successful!
making call for chunk number 390
call successful!
making call for chunk number 391
call successful!
making call for chunk number 392
call successful!
making call for chunk number 393
call successful!
making call for chunk number 394
call successful!
making call for chunk number 395
call successful!
making call for chunk number 396
call successful!
making call for chunk number 397
call successful!
making call for chunk number 398
call successful!
making call for chunk number 399
call successful!
making call for chunk number 400
call successful!
Getting Android apps info...

In [9]:
# Export the file to csv and save to base layer folder
df_app_full_info.to_csv('data/base/st_api_app_full_info_{}.csv'.format(timestamp), index=False)

**Get Raw File: Mapping Publisher to Apps (Top Down)**

In [7]:
# Manually Prepared

**Get Raw File: Mapping Publisher to Apps and Publisher IDs (Top Down)**

In [20]:
# Path to Mapping Publisher to Apps Raw File
path_mapping_publisher_to_apps = 'data/base/st_manualsearch_mapping_publisher_to_apps_top_down_2025-10-28.csv'

In [21]:
# Retrieve the publisherid from ST
df_mapping_publisher_to_apps_and_publisherids = lsdp.create_mapping_publisher_to_apps_publisherids(path_mapping_publisher_to_apps, api_key, base_url)

Reading csv file: mapping publisher to apps...
Get ST publisher info for ios apps...
making call for chunk number 1
call successful!
making call for chunk number 2
call successful!
making call for chunk number 3
call successful!
making call for chunk number 4
call successful!
Get ST publisher info for Android apps...
making call for chunk number 1
call successful!
making call for chunk number 2
call successful!
making call for chunk number 3
call successful!
making call for chunk number 4
call successful!

In [22]:
# Export the file to csv and save to base layer folder
df_mapping_publisher_to_apps_and_publisherids.to_csv('data/base/st_api_mapping_publisher_to_apps_publisherids_top_down_{}.csv'.format(timestamp), index=False)

**Get Raw File: Mapping Publisher to Publisher ID and Revenue Multiplier (Bottom Up)**

In [12]:
# Manually Prepared

**Get Raw File: Mapping App to Revenue Multiplier (Special Cases)**

In [ ]:
# Manually Prepared

**Get Raw File: App Performance (Daily)**

In [6]:
# Read file App Full Info (Adjusted)
df_app_full_info_adjusted = pd.read_csv('data/staging/st_app_full_info_adjusted_1763107898.csv', low_memory=False)

In [ ]:
# Run the function to fetch the data and export to json
app_performance_data = lsdp.create_table_app_performance_grouped_by_game_daily(
    api_key, 
    base_url, 
    str_start_date = '2014-01-01', 
    str_end_date = (date.today() - timedelta(days=3)).isoformat(), 
    df_app_full_info_adjusted, 
    json_export_path = 'data/base')

# Staging Layer

**Get Staging File: Mapping Publisher to Publisher ID and Revenue Multiplier (Full)**

In [6]:
# Read file Mapping Publisher to Apps and Publisher IDs (Top Down)

data_types = {
    "os_x": "string",
    "cleaned_publisher_name": "string",
    "game_name": "string",
    "sensor_tower_link": "string",
    "app_id_trimmed": "string",
    "publisher_id": "string",
    "publisher_name": "string",
}

df_mapping_publisher_to_apps_and_publisherids_top_down = pd.read_csv(
    'data/base/st_api_mapping_publisher_to_apps_publisherids_top_down_2025-10-28.csv',
    dtype = data_types
)

In [7]:
# Read file Mapping Publisher to Publisher ID and Revenue Multiplier (Bottom Up)

data_types = {
    "cleaned_publisher_name": "string",
    "publisher_id": "string",
    "publisher_name": "string",
    "revenue_multiplier": "int64"
}

df_mapping_publisher_to_publisherid_revenue_multiplier_bottom_up = pd.read_csv(
    'data/base/st_manualsearch_mapping_publisher_to_publisherids_revenue_multiplier_bottom_up_2025-10-31.csv',
    dtype = data_types
)

In [8]:
# Merge the top-down and bottom-up tables into a full mapping

In [9]:
df_mapping_publisher_to_publisherid_revenue_multiplier_full = lsdp.create_mapping_publisher_to_publisherids_revenue_multiplier(
    df_mapping_publisher_to_apps_and_publisherids_top_down,
    df_mapping_publisher_to_publisherid_revenue_multiplier_bottom_up
)

Merging is complete, now have the full mapping table. But need to double check for rows having null publisher_id
These are rows having null publisher_id:
             cleaned_publisher_name publisher_id publisher_name  \
138  CTCP Giai Tri Thien Thuong Hoa         <NA>           <NA>

     revenue_multiplier
138                   3
Best to check again these rows. Potential reasons: apps become inactive in the country of interest; app id typo; app id changed by SensorTower; etc.
Removing these rows from the merged mapping table...

In [10]:
# Export the file to csv and save to staging layer folder
df_mapping_publisher_to_publisherid_revenue_multiplier_full.to_csv("data/staging/st_mapping_publisher_to_publisherids_revenue_multiplier_full_{}.csv".format(timestamp),index=False)

**Get Staging File: App Full Info (Adjusted)**

In [6]:
# Read file App Full Info
df_app_full_info = pd.read_csv('data/base/st_api_app_full_info_2025-10-27.csv', low_memory=False)

In [7]:
# Read file Mapping Publisher to Publisher ID and Revenue Multiplier (Full)
df_mapping_publisher_to_publiserid_and_revenue_multiplier_full = pd.read_csv('data/staging/st_mapping_publisher_to_publisherids_revenue_multiplier_full_2025-10-31.csv', low_memory=False)

In [8]:
# Read file Mapping App to Revenue Multiplier (Special Cases)
df_mapping_app_to_revenue_multiplier_special_case = pd.read_csv('data/base/st_mapping_app_to_revenue_multiplier_special_case_1763095974.csv', low_memory=False)

In [9]:
# Cast cleaned_publisher_name and revenue_multiplier to App Full Info to get App Full Info (Adjusted)
df_app_full_info_adjusted = lsdp.add_cleaned_publisher_name_and_revenue_multiplier_to_app_full_info(
    df_app_full_info,
    df_mapping_publisher_to_publiserid_and_revenue_multiplier_full
)

In [27]:
# Adjust the App Full Info list again for special cases
df_app_full_info_adjusted_again = lsdp.adjust_cleaned_publisher_name_and_revenue_multiplier_of_app_full_info_special_cases(
    df_app_full_info_adjusted,
    df_mapping_app_to_revenue_multiplier_special_case
).drop_duplicates()

In [34]:
# Export the file to csv and save to staging layer folder
df_app_full_info_adjusted_again.to_csv('data/staging/st_app_full_info_adjusted_{}.csv'.format(timestamp), index=False)

**Get Staging File: App Performance (Daily) - Revenue Adjusted [NEED TO EDIT LATER WITH CORRECT FILE PATHS & DO SOME REFACTOR]**

In [22]:
# Read file App Full Info (Adjusted)
df_app_full_info_adjusted = pd.read_csv('data/staging/st_app_full_info_adjusted_1763107898.csv', low_memory=False)

In [14]:
# Specify the path of input and output
src_path = "data/staging/st_app_performance_daily_1764146538.json"
file_timestamp = os.path.basename(src_path).split("_")[-1].split(".")[0]
dst_path = "data/staging/st_app_performance_daily_{}_revenue_adjusted.json".format(file_timestamp)

In [ ]:
# Run the function for adjusting and streaming
lsdp.stream_and_adjust_app_performance_daily_json_file(
    src_path,
    dst_path,
    df_app_full_info_adjusted
)

In [41]:
# Get the mapping app_id => revenue_multiplier
df_mult = df_app_full_info_adjusted[df_app_full_info_adjusted['revenue_multiplier']!=1][['app_id','revenue_multiplier']].copy()
revenue_factor_by_app = (
    df_mult.set_index("app_id")["revenue_multiplier"].to_dict()
)

In [46]:
def adjust_revenue(rec):
    aid_str = str(rec.get("aid"))
    factor = revenue_factor_by_app.get(aid_str)

    # If no multiplier (or factor == 1), just return as-is
    if factor is None or factor == 1:
        return rec

    # iOS: ir = iPhone revenue, ar = iPad revenue
    if "ir" in rec and rec["ir"] is not None:
        rec["ir"] = rec["ir"] * factor
    if "ar" in rec and rec["ar"] is not None:
        rec["ar"] = rec["ar"] * factor

    # Android: r = Android revenue
    if "r" in rec and rec["r"] is not None:
        rec["r"] = rec["r"] * factor

    return rec

In [49]:
# Streaming and adjusting original app performance data file to adjusted app performance data file
src_path = "data/staging/st_app_performance_daily_1764146538.json"
dst_path = "data/staging/st_app_performance_daily_1764146538_revenue_adjusted.json"

total_bytes = os.path.getsize(src_path)

with open(src_path, "rb") as src, \
     open(dst_path, "w", encoding="utf-8") as dst, \
     tqdm(total=total_bytes, unit="B", unit_scale=True, desc="Processing") as pbar:

    dst.write("[\n")
    first = True

    for rec in ijson.items(src, "item"):
        rec = adjust_revenue(rec)

        if not first:
            dst.write(",\n")
        first = False

        json.dump(rec, dst, ensure_ascii=False)

        # update progress to current file position
        pbar.update(src.tell() - pbar.n)

    dst.write("\n]\n")

rocessing: 100%|█████████████████████████████████████████████████████████████████| 7.10G/7.10G [22:15<00:00, 5.32MB/s]

In [51]:
# Checking: read the output json file
def count_items_with_progress(path):
    total_bytes = os.path.getsize(path)
    count = 0

    with open(path, "rb") as f, \
         tqdm(
             total=total_bytes,
             unit="B",
             unit_scale=True,
             desc=f"Counting {os.path.basename(path)}"
         ) as pbar:

        # 'item' iterates each element of the top-level JSON array
        for _ in ijson.items(f, "item"):
            count += 1
            # advance progress to current file position
            pbar.update(f.tell() - pbar.n)

    print(f"{path} → {count:,} records")
    return count


count_items_with_progress("data/staging/st_app_performance_daily_1764146538.json")
count_items_with_progress("data/staging/st_app_performance_daily_1764146538_revenue_adjusted.json")

ounting st_app_performance_daily_1764146538.json: 100%|██████████████████████████| 7.10G/7.10G [04:24<00:00, 26.9MB/s]

data/staging/st_app_performance_daily_1764146538.json → 52,747,279 records

Counting st_app_performance_daily_1764146538_revenue_adjusted.json: 100%|█████████| 4.45G/4.45G [04:11<00:00, 17.7MB/s]

data/staging/st_app_performance_daily_1764146538_revenue_adjusted.json → 52,747,279 records

52747279

In [42]:
revenue_factor_by_app

{'6476554439': 3,
 '904890205': 20,
 '1521771561': 3,
 '1621483610': 3,
 '6443442131': 3,
 '6740561197': 3,
 '6740611773': 3,
 '6747331870': 3,
 '1431610213': 3,
 '6504474986': 3,
 '6451137140': 3,
 '1127157068': 15,
 '1159236542': 3,
 '1261834568': 3,
 '1577123983': 3,
 '1438376417': 3,
 '1469164964': 3,
 '6466761725': 15,
 '6479692189': 3,
 '1583717977': 3,
 '6747154050': 3,
 '6444060858': 3,
 '1591546813': 3,
 '1588009371': 15,
 '6448143057': 3,
 '6717587690': 3,
 '6740536674': 15,
 '799319182': 20,
 '887752917': 20,
 '1528287521': 15,
 '6633416904': 15,
 '1573033171': 3,
 '1495625837': 3,
 '6446198142': 3,
 '1616630100': 3,
 '6499431484': 3,
 '1665137451': 3,
 '6478189835': 3,
 '6479636678': 3,
 '6476176288': 3,
 '1521411821': 3,
 '6467690444': 3,
 '6478138913': 3,
 '638689075': 3,
 '6480434384': 3,
 '6446388135': 3,
 '6451463643': 15,
 '1546606867': 15,
 '6738641269': 3,
 '1460786661': 3,
 '1633945760': 3,
 '6478901170': 15,
 '6504267531': 15,
 '1071744151': 3,
 '1593143999': 3,
 '1502412815': 3,
 '1467842750': 3,
 '1521779642': 3,
 '1582020814': 15,
 '6479231049': 3,
 '6446610044': 3,
 '1417141579': 3,
 '1444754600': 3,
 '1464689103': 3,
 '1587704770': 3,
 '6737103277': 15,
 '1559698151': 3,
 '1465097065': 3,
 '6453690496': 3,
 '1306451576': 3,
 '6471930550': 3,
 '1453657959': 15,
 '6472704324': 3,
 '6469768541': 3,
 '1501476139': 3,
 '1635925350': 3,
 '1477780217': 3,
 '6449825814': 3,
 '1632354684': 3,
 '6448864292': 3,
 '6502928253': 15,
 '1489436528': 15,
 '1546353393': 3,
 '6456407206': 3,
 '6502480712': 3,
 '6596734272': 3,
 '6480383911': 3,
 '6443444765': 3,
 '1451281983': 3,
 '1570594577': 3,
 '1472743924': 3,
 '6738091256': 3,
 '6480404570': 3,
 '1448024270': 3,
 '1616610297': 3,
 '1620319514': 15,
 '6444932771': 3,
 '6480410032': 3,
 '1438493375': 3,
 '6446750210': 3,
 '1518968894': 3,
 '6449966646': 15,
 '1569151989': 3,
 '1633394133': 3,
 '1300146617': 15,
 '1480516829': 15,
 '6474838818': 15,
 '1612175933': 15,
 '1670791259': 3,
 '6468433525': 15,
 '6738572450': 3,
 '6470252900': 3,
 '6443668820': 15,
 '6461417156': 3,
 '1455953893': 3,
 '6466396468': 3,
 '6742647964': 3,
 '1531280382': 15,
 '6475714083': 3,
 '6738905182': 3,
 '1672472869': 3,
 '6447612680': 3,
 '6737220373': 3,
 '1583880258': 3,
 '1547396989': 15,
 '1414804192': 15,
 '1446390036': 3,
 '1612001355': 3,
 '6742177455': 3,
 '1156810287': 3,
 '1202529338': 3,
 '1221871390': 3,
 '6448143284': 15,
 '6742437694': 3,
 '1515449050': 15,
 '1438396625': 15,
 '1012864419': 15,
 '6736925794': 3,
 '1434052677': 3,
 '6448943160': 3,
 '6478959083': 3,
 '1052983610': 15,
 '1453469177': 3,
 '6550905396': 3,
 '1281535229': 3,
 '942043135': 15,
 '1474935601': 3,
 '1634389457': 3,
 '1416604843': 15,
 '1435297178': 15,
 '1464658787': 15,
 '1514341641': 3,
 '1557176966': 3,
 '1590154620': 3,
 '1579889775': 3,
 '6740482237': 3,
 '1495055713': 3,
 '1549824326': 3,
 '1607282320': 3,
 '6472133989': 15,
 '6499399033': 3,
 '1370300345': 3,
 '6738371242': 3,
 '1596859213': 3,
 '6450526727': 15,
 '1199882006': 3,
 '6743202626': 3,
 '1483753846': 3,
 '6480037958': 3,
 '1547943736': 3,
 '554597348': 3,
 '562989701': 3,
 '578250301': 3,
 '578252579': 3,
 '6443998295': 15,
 '6745683002': 3,
 '6736819155': 3,
 '6475273991': 3,
 '1230292637': 3,
 '1581941519': 3,
 '1593573796': 3,
 '6544794058': 3,
 '1450238838': 3,
 '1537216540': 3,
 '1585602211': 3,
 '1098189387': 3,
 '1610291670': 15,
 '6447750572': 3,
 '6514312909': 3,
 '6475273921': 3,
 '1197441484': 3,
 '6443462521': 15,
 '1491703061': 3,
 '6474715805': 15,
 '1520159653': 3,
 '1529414550': 3,
 '1533615861': 15,
 '6447841794': 3,
 '1619055583': 3,
 '1439862260': 15,
 '1560124228': 3,
 '1570746506': 15,
 '6498472624': 3,
 '1498402668': 3,
 '1125893746': 15,
 '1485542024': 3,
 '6738274677': 3,
 '6443760593': 3,
 '1523256630': 3,
 '6476652682': 15,
 '6748971774': 3,
 '1509373363': 3,
 '6446679128': 3,
 '1372629721': 3,
 '1418864900': 3,
 '1428316113': 3,
 '1441600774': 3,
 '1465849529': 3,
 '1501618516': 3,
 '1501619128': 3,
 '1504586985': 3,
 '1504587645': 3,
 '1439414645': 15,
 '1477800522': 3,
 '6670604287': 15,
 '6738761685': 15,
 '6739530152': 3,
 '963664008': 3,
 '996809719': 3,
 '1118620009': 3,
 '1578623489': 3,
 '1641642655': 3,
 '1376515087': 3,
 '1464502423': 3,
 '1516465879': 3,
 '6739119850': 3,
 '1610048857': 3,
 '6737467132': 3,
 '6448320673': 3,
 '1645497690': 15,
 '6450761748': 3,
 '1207998539': 3,
 '1068204657': 3,
 '6479236752': 3,
 '6479175676': 3,
 '6475951069': 3,
 '1619055257': 3,
 '6448333104': 3,
 '6480329405': 3,
 '1358604343': 3,
 '6472019436': 3,
 '6474231541': 15,
 '6446393713': 3,
 '1572417749': 3,
 '1624412609': 3,
 '908192673': 15,
 '1058728157': 15,
 '1545808948': 3,
 '6463065706': 3,
 '6504342170': 3,
 '1546174938': 3,
 '1613851348': 3,
 '1217791326': 3,
 '6476137851': 3,
 '1504054504': 3,
 '1632874166': 15,
 '1522842979': 3,
 '6467398199': 3,
 '1541275013': 3,
 '1637396239': 3,
 '6480159278': 3,
 '1562608318': 3,
 '6445982244': 3,
 '6502498607': 3,
 '1642861858': 3,
 '1643854223': 15,
 '6478273595': 3,
 '6739808002': 3,
 '6743733953': 3,
 '1610703929': 3,
 '1287508973': 3,
 '1619722656': 3,
 '6504784958': 3,
 '1523281185': 3,
 '6450900363': 3,
 '6479681223': 3,
 '6478090188': 3,
 '6744964055': 3,
 '6590610850': 3,
 '6466970768': 3,
 '6505037845': 15,
 '6742124069': 3,
 '1599056590': 3,
 '1638876595': 3,
 '1441417054': 3,
 '950176941': 15,
 '6451477469': 3,
 '1297293884': 3,
 '1624503075': 3,
 '1132499977': 3,
 '1174766451': 3,
 '1505731053': 3,
 '1502971131': 15,
 '1613648368': 15,
 '403710610': 3,
 '426911698': 3,
 '456887491': 3,
 '463695183': 3,
 '467044485': 3,
 '467046915': 3,
 '467589706': 3,
 '473917756': 3,
 '473920065': 3,
 '574769161': 3,
 '574771160': 3,
 '664467619': 3,
 '664575829': 3,
 '708986361': 3,
 '725437153': 3,
 '1539383751': 3,
 '1521236603': 3,
 '6749760949': 3,
 '1541992176': 15,
 '6462862543': 3,
 '1208729802': 3,
 '1570767171': 3,
 '6599836402': 3,
 '1577970257': 3,
 '6448781122': 3,
 '1141358828': 3,
 '6478379359': 3,
 '1531825274': 3,
 '1479050948': 3,
 '1479281298': 3,
 '6480159814': 3,
 '406889139': 3,
 '6450002245': 3,
 '1447933800': 3,
 '1621098895': 15,
 '1531831962': 3,
 '6742780202': 3,
 '1436932265': 3,
 '1505720247': 3,
 '1277551859': 15,
 '6740510300': 3,
 '6449674450': 3,
 '1089079153': 15,
 '1150288115': 15,
 '1150331854': 15,
 '1150337432': 15,
 '1427128108': 15,
 '1427414541': 15,
 '6475763562': 15,
 '894956701': 20,
 '908617867': 20,
 '6446672928': 3,
 '6473259128': 3,
 '6502440184': 3,
 '1078191559': 15,
 '6745806781': 3,
 '1015763729': 3,
 '1558779269': 15,
 '1574489575': 3,
 '1589886973': 15,
 '6740690310': 3,
 '6477903252': 15,
 '6738380021': 3,
 '1051206681': 15,
 '1073852575': 15,
 '1393015117': 3,
 '1488431275': 3,
 '964827011': 3,
 '6443894073': 3,
 '6504058743': 3,
 '6451180763': 3,
 '1568659894': 15,
 '1578835721': 3,
 '1195621598': 3,
 '6504593009': 3,
 '6596747799': 3,
 '1070492711': 3,
 '1261675692': 15,
 '1463369328': 3,
 '6503333670': 3,
 '993081569': 15,
 '1017635295': 15,
 '1023316377': 15,
 '1058716053': 15,
 '6575363756': 3,
 '6739763390': 3,
 '1463380174': 3,
 '1577149017': 3,
 '6471364763': 3,
 '6450447751': 3,
 '1428475506': 15,
 '6468942281': 3,
 '1618158368': 3,
 '6738688188': 15,
 '1471932438': 3,
 '1638086822': 15,
 '6737226348': 15,
 '1572615571': 15,
 '6453691541': 3,
 '6478485058': 3,
 '1313204995': 3,
 '6502153297': 3,
 '1642487048': 3,
 '445297616': 15,
 '853000739': 15,
 '1236412425': 3,
 '1507180749': 3,
 '1496612433': 3,
 '6446024007': 3,
 '6738161495': 3,
 '1607048270': 3,
 '6450411268': 3,
 '6473467482': 3,
 '1470911692': 3,
 '6478997449': 3,
 '6738500946': 15,
 '553834731': 3,
 '1436138195': 3,
 '1040134392': 3,
 '1105855019': 3,
 '1465688043': 15,
 '1477030970': 15,
 '1238026766': 15,
 '1478858105': 3,
 '1451307336': 3,
 '6739480917': 3,
 '1172124096': 15,
 '1492680134': 3,
 '1588665666': 3,
 '1072032563': 3,
 '1091188714': 3,
 '1104555626': 3,
 '6467180067': 3,
 '6612015169': 3,
 '6743143064': 3,
 '1602460179': 3,
 '1127240206': 3,
 '1663702161': 3,
 '1565125572': 3,
 '6450451786': 3,
 '1604207548': 3,
 'vn.linh.kiem.chi.mong': 3,
 'com.global.antgamevn': 3,
 'com.vn.sl.google': 3,
 'gsn.game.talanew': 20,
 'gsn.game.talanew3': 20,
 'gsn.game.zingplaynew3': 20,
 'gsn.game.zingplaytala': 15,
 'com.xxyx.sea': 3,
 'com.xxyx.vn': 3,
 'com.allstarunion.myths.vn': 3,
 'com.iccgame.grail': 3,
 'com.readygo.dark.gphh': 3,
 'au2.audition.vtcgame.dancing.aumobile.gamethoitrang': 3,
 'ship.simulator.river.climb': 3,
 'sea.reignofwarlords': 15,
 'com.nekki.shadowfight2.paid': 3,
 'com.vtcmobile.longchien': 3,
 'com.vtcmobilejsc.phuckichvtc': 3,
 'com.gmt.huntersaga.gamota': 3,
 'vnggames.tqts.mmo.vn': 15,
 'com.jwsvn.gg': 3,
 'com.more.lastfortress.gpvn': 3,
 'com.vtcmobile.thanhkiemluanhoi': 3,
 'com.zps.caro': 15,
 'com.lilithgames.wgame.android.jp': 3,
 'com.lilithgames.wgame.android.kr': 3,
 'com.wondergames.warpath.gp': 3,
 'com.wondergames.warpath.gp.ptr': 3,
 'com.allstarunion.ta.vn': 3,
 'com.zzsj.vn': 3,
 'vgp.dev.thanh.van.kiem': 3,
 'vn.kvtm.js': 15,
 'vn.kvtm.khuvuontrenmay': 15,
 'com.gosu.cuuduong2': 3,
 'vn.vplay.huyentuong.t021a': 3,
 'vng.games.kiemvu.phong.idle.rpg': 15,
 'com.gsn.zps.full': 15,
 'com.vng.lineage2mvn': 15,
 'gsn.game.zingplaynew': 15,
 'shooter.online.warplanes': 3,
 'com.sgyml.vn.an': 3,
 'gsn.zps.thoiloan': 15,
 'com.vntth.sgzzlb.gp.vn': 3,
 'rail.road.tycoon': 3,
 'com.nobodyshot.POLYWAR': 3,
 'vn.funtap.tannhatkiem': 3,
 'vn.funtap.thucsonthienhachien': 3,
 'vn.vplay.khoinguyen.t016a': 3,
 'com.vtc.tt11': 3,
 'com.archosaur.vn.dr.gp': 3,
 'com.shg.sg416': 3,
 'vn.dev.thienvu.thanvuong': 3,
 'com.playrix.township': 3,
 'vn.huyenthoaing.gg': 3,
 'com.tg.yls.vn': 3,
 'vn.gosu.atomarena': 3,
 'com.riotgames.league.teamfighttacticsvn': 15,
 'vn.pg1.vltk1m': 15,
 'com.azurinteractive.StarForces': 3,
 'com.global.byvn.google': 3,
 'vn.funtap.kiemma3d': 3,
 'com.camelgames.superking': 3,
 'com.mechanist.poi.vn': 3,
 'thelegendofneverland.thelegend.neverland.openworld.gamehay.trochoi.vtc.game': 3,
 'vng.games.gs1.phongthan.mobile.com': 15,
 'vng.games.taydu.ngokhong.idle.rpg': 15,
 'com.vtcmobile.hcm.g170801.vqtm': 3,
 'com.vtcmobile.phongvanchivtc': 3,
 'gsn.tdf.vn': 15,
 'vn.funtap.daihieptaptap': 3,
 'com.azurgames.dinosaurs': 3,
 'com.MelsoftGames.FamilyIslandFarm': 3,
 'com.funtap.thienkiemmobile': 3,
 'train.railroad.climb.simulator': 3,
 'com.global.aoempiresvn': 3,
 'vng.games.tamquoc.idle.rpg': 15,
 'and.onemt.boe.vi.appota': 3,
 'com.camelgames.ig': 3,
 'com.lilithgame.isoland2.gp.mf': 3,
 'com.lilithgame.isoland2.gpen': 3,
 'vn.funtap.danhtuong.truyenky': 3,
 'dev.manga.bachay': 3,
 'gamebongda.bongda.vuabongda.football.kingoffootball.trochoi.mienphi.game.online.vtc': 3,
 'com.gs2.ttl3dmb': 15,
 'com.mobilegame.mn12': 3,
 'com.shg.sg401new': 3,
 'com.gmt.tamquoc.lienthanhchien': 3,
 'com.vtcmobile.autop': 3,
 'com.gosu.cdtc': 3,
 'com.papegames.nn4.vn': 3,
 'com.miHoYo.bh3oversea_vn': 3,
 'com.vtcmobile.wows': 3,
 'vng.games.mu.webzen.online': 15,
 'com.vng.psvkcvn': 15,
 'dev.vgp.yeu.linh.gioi': 3,
 'vn.vgpjsc.dauhonsu': 3,
 'com.snmjglo.google': 3,
 'vn.gosu.nhatdaithienton': 3,
 'com.redriver.shjjc': 3,
 'pocket.tales': 3,
 'com.pocket.shooter': 3,
 'com.redriver.gp.vi.lzgwy': 3,
 'com.shg.sg381': 3,
 'com.more.dayzsurvival.gpvn': 3,
 'com.redtailworks.slimetd': 3,
 'com.szckhd.jwgly.azkr': 3,
 'com.szckhd.jwgly.azvn': 3,
 'vng.games.thienlong.kiemhiep3d.mobile': 15,
 'com.hxmjl.vn.an': 3,
 'com.elex.twdsaw.vn': 3,
 'com.igg.android.castleclashvn': 3,
 'com.camelgames.wod': 3,
 'vng.games.taydu.chienthuat.online': 15,
 'com.onemt.and.kc.vn': 3,
 'com.shg.sg336': 3,
 'com.dts.freefiremax': 15,
 'com.dts.freefireth': 15,
 'com.vnggames.ghoststory': 15,
 'com.vng.playtogether': 15,
 'com.vtcfun.fun.cardgame.boardgame.vtc': 3,
 'vng.games.my.cafe.hello.coffee': 15,
 'com.shg.sg280': 3,
 'com.shg.sg434': 3,
 'com.shg.sg434new': 3,
 'com.global.dqvn': 3,
 'com.allstarunion.beastlord.vn': 3,
 'com.vtc.tapkich': 3,
 'com.zps.spfvn': 15,
 'com.playrix.manormatters': 3,
 'vn.vplay.vohiep.t027a': 3,
 'com.gmt.lucdaoluanhoi': 3,
 'com.riotgames.league.wildriftvn': 15,
 'com.vtcmobile.dragonheroes': 3,
 'com.vtcmobile.mn16': 3,
 'com.Lilith.Abi': 3,
 'vn.vplay.dauthantuyetthe.t010a': 3,
 'com.shg.sg391': 3,
 'vn.dev.ma.kiem.vo.song': 3,
 'com.vng.hpqtvn': 15,
 'vng.game.sky.fantasy.song.vn': 15,
 'com.hhgame.mcggvn': 3,
 'com.vtcmobile.xcity': 3,
 'vn.tamgioi.anhhung': 3,
 'vn.vplay.tamquocchi.t025a': 3,
 'com.vng.pubgmobile': 15,
 'com.vng.thieunien3qvng': 15,
 'com.garena.game.westtw': 15,
 'com.fun.lastwar.vn.gp': 3,
 'ru.azurinteractive.robotwarfare': 3,
 'com.dinhphong2.gg': 3,
 'vn.funtap.chuyensinh': 3,
 'com.herogames.crisisaction': 3,
 'com.zps.cotyphu.af': 15,
 'com.gamedevltd.wwh': 3,
 'com.angame.ddtank.vn': 15,
 'com.angame.gunnymobi.vn': 15,
 'com.angame.mwork.vn': 15,
 'com.gmt.hoathienkiepgamota': 3,
 'com.eoc.google.watt': 3,
 'com.garena.game.fcsac': 15,
 'com.garena.game.fctw': 15,
 'com.vng.speedvn': 15,
 'com.vtcmobile.thk': 3,
 'com.dc.gok.google': 3,
 'com.shg.sg328': 3,
 'com.archosaur.vn.sgzgc.gp': 3,
 'com.world.war.defence': 3,
 'com.alphainteractive.sniperawpshooter': 3,
 'roe.vn.riseofempires': 3,
 'com.archosaur.vn.yslzm.gp': 3,
 'com.silkroad.mb': 3,
 'vn.funtap.phuonghoang.camtu': 3,
 'com.lin2vn': 3,
 'com.zjws.sea.vn': 3,
 'com.topwar.gp.vn': 3,
 'com.vng.thiennhaiminhnguyetdaovng': 15,
 'com.playrix.wildscapes_new.google': 3,
 'com.playrix.zoo_m3.gplay': 3,
 'com.tg.dpcq2.vn': 3,
 'com.vtcmobile.phongmachien': 3,
 'vn.dev.tuma.truyenky': 3,
 'com.mobi389.murom': 3,
 'com.nekki.vector': 3,
 'com.nekki.vector.paid': 3,
 'com.vtcmobile.ghbp': 3,
 'zps.games.bida3d.vn': 15,
 'com.pergame.starliteden': 3,
 'com.pergame.starlitedenru': 3,
 'com.ddup.zombiewaves.zw.vn': 3,
 'vn.vgpjsc.langvan.chikiem': 3,
 'com.gmt.trutien': 3,
 'com.ptct.gp.vn': 3,
 'com.slsm.an.en': 3,
 'com.slsmus.an.watt': 3,
 'com.com2us.smon.normal.freefull.google.vn.android.common': 3,
 'com.nekki.ninjaparty': 3,
 'com.tg.ysr.vn': 3,
 'com.vizorapps.mahjong': 3,
 'com.vtcmobile.thaicophong': 3,
 'vnggames.gs1.volam3': 15,
 'vn.thuongkhungchikiem.funtap': 3,
 'com.igg.android.vikingrisevn': 3,
 'com.gamedevltd.modernstrike': 3,
 'com.m3.vn': 15,
 'com.lilithgame.hgame.gp': 3,
 'com.lilithgame.hgame.gp.jp': 3,
 'com.lilithgame.hgame.gp.kr': 3,
 'com.lilithgames.hgame.gp.id': 3,
 'vn.funtap.tuyetthevolam': 3,
 'com.roblox.client.vnggames': 15,
 'com.funtapgame.kart.rushplus.kartm': 3,
 'com.igg.android.doomsdaylastsurvivorsvn': 3,
 'com.vng.fwvn': 15,
 'com.aladinfun.piggytravel.android.vietnam': 3,
 'com.vtc.tco': 3,
 'com.exoticmatch.game': 3,
 'com.gs2.mua': 15,
 'com.shgame.sg326': 3,
 'game.bida.vng': 15,
 'com.vtcmobile.lienminhstickman': 3,
 'com.gmt.kiemthanfinalfantasy': 3,
 'com.jsjsvn.google': 3,
 'com.vng.vltkm': 15,
 'com.shg.sg433': 3,
 'com.ddup.zombiewaves.zw': 3,
 'com.ddup.zombiewaves.zw.ru': 3,
 'com.mobigame.qjxx': 3,
 'com.vng.mf.liteuamo': 15,
 'com.oasis.immortal': 3,
 'com.and.vn.daqin': 3,
 'com.shg.sg295': 3,
 'vng.games.thienlong.tlbb3d.kiemhiep': 15,
 'dev.phong.van.kiem': 3,
 'com.wod.ag.global': 3,
 'com.vtcmobile.tramtienquyetobb': 3,
 'com.wsy.google.hk.wansuiye': 3,
 'com.wsy.google.wansuiye': 3,
 'com.wsy.google.wansuiye.en': 3,
 'com.wsy.google.wansuiye.fr': 3,
 'com.wsy.google.wansuiye.id': 3,
 'com.wsy.google.wansuiye.jp': 3,
 'com.wsy.google.wansuiye.kr': 3,
 'com.wsy.google.wansuiye.ru': 3,
 'com.wsy.google.wansuiye.th': 3,
 'com.igg.android.mobileroyalevn': 3,
 'vn.pp.dt3q': 15,
 'com.garena.game.df': 15,
 'com.tkc.an.funiverse': 3,
 'vn.vplay.chuongmon.t022a': 3,
 'vn.zps.tl2': 15,
 'air.com.limboworks.honorofcup.appota.sea': 3,
 'com.gmt.tamquoc.gamota': 3,
 'com.camelgames.aoz': 3,
 'com.camelgames.aoz.arabic': 3,
 'com.soha.evony': 3,
 'com.kingsgroup.sos.vn': 3,
 'com.vtcmobile.hoasonkiemthe': 3,
 'vn.vplay.chiengioi4d.t002a': 3,
 'com.iccgame.silkroadonline.androidvn': 3,
 'com.shgame.sg314': 3,
 'vn.funtap.daitienminhdidauthe': 3,
 'com.vtcmobile.talachienthan': 3,
 'com.garena.game.caithetranhhung': 15,
 'com.vtcmobile.aumobilevtc': 3,
 'com.zlya.sabuk': 3,
 'com.allstarunion.wow.vn': 3,
 'com.shg.sg292': 3,
 'com.melesta.coffeeshop': 3,
 'com.rapidfiregames.backpackbrawl': 3,
 'vn.funtap.dauphamobile': 3,
 'com.ddj.vn': 3,
 'vn.dev.hiepkhach.chica': 3,
 'vn.dev.thuc.than.ky': 3,
 'com.gmt.hiepkhachgiangho': 3,
 'com.gp.we': 3,
 'com.vng.mf.uamo': 15,
 'com.vtcmobile.mn09': 3,
 'ufc.sieusaobongda.bongda.sieusao.fifa.game.thethao.online.vtc.game': 3,
 'com.gp.lttq': 3,
 'com.giant.supersus': 3,
 'com.je.supersus': 3,
 'com.mobigame.tt12': 3,
 'com.huyenthoai.hvht': 3,
 'com.play.rosea': 3,
 'com.vng.tanngoalong': 15,
 'com.wzlr.sea': 3,
 'vn.zalo.ngoalongmb': 15,
 'com.mobigame.cuongma2': 3,
 'com.nekki.shadowfight': 3,
 'com.nekki.shadowfighttv': 3,
 'com.dieselpuppet.detectivestory': 3,
 'com.funtap.vtqvn': 3,
 'com.HoYoverse.NapVn': 3,
 'com.gsn.newca': 15,
 'com.tjb.an.en4399': 3,
 'com.zingplay.cabeo': 15,
 'zps.myfish.vn': 15,
 'com.vtcmobile.chienthankynguyen': 3,
 'com.vtcmobile.ctkn': 3,
 'com.vtc.nguthansu': 3,
 'com.global.frxxvn': 3,
 'com.gosu.gamo.hogiachunhan': 3,
 'com.hh.xherovn.moblie': 3,
 'com.mrtgd.sea': 3,
 'com.vtcmobile.qslm': 3,
 'vnggames.topeleven.football.soccermanager': 15,
 'com.seaofconquest.googlevn': 3,
 'com.vtcmobile.tayduky': 3,
 'com.gmt.anhhungxadieu': 3,
 'vn.vplay.lienminhphapsu.a1': 3,
 'com.netease.g78na.vn': 3,
 'com.shg.sg426': 3,
 'com.vtc.tlvd': 3,
 'offroad.racing.game': 3,
 'vn.funtap.kynuhoangcung': 3,
 'com.shg.sg438': 3,
 'vn.vplay.tamquocdailuc.t019a': 3,
 'com.netease.newspikevn': 3,
 'vn.vplay.kiemlai.t024a': 3,
 'rts.bunker.wars': 3,
 'vng.games.dream.mobile': 15,
 'dev.ngulong.kiem3d': 3,
 'com.vng.gpdttkvn': 15,
 'com.vng.tinhvan.dota': 15,
 'us.kick9.k3000000013.c3101000001': 3,
 'com.miHoYo.GenshinImpact.vn': 3,
 'com.Nobodyshot.kuboom': 3,
 'com.gmt.tienkiemkyduyen3d': 3,
 'com.nekki.shadowfight.shades': 3,
 'com.gmt.dolong3d': 3,
 'com.gmt.ythien': 3,
 'com.riotgames.legendsofruneterravn': 15,
 'vnggames.volam.kiemthe.origin': 15,
 'com.playrix.fishdomdd.gplay': 3,
 'io.randomco.travel': 3,
 'com.BastardGames.HiredHeroesMedievalWarfare': 3,
 'com.vng.tanomg3q': 15,
 'com.daichien.mobile': 3,
 'com.vtcmobile.daichienfull': 3,
 'com.dragon.sails': 3,
 'com.global.ztmslgvn': 3,
 'vn.gosu.cuuam2d': 3,
 'puzzle.merge.hotel.empire': 3,
 'vn.dev.mongkiem.tieudao': 3,
 'com.tg.jsxw.vn': 3,
 'com.zillionwhales.mushroomwars2': 3,
 'vn.gosu.cuuam': 3,
 'com.nekki.shadowfightarena': 3,
 'com.rxsj.an.en4399': 3,
 'com.gsn.getmoney': 15,
 'com.moonactive.coinmaster': 3,
 'com.yuewan.tgvn': 3,
 'com.gmt.thankhucmobile': 3,
 'com.vng.metalslug.rambolun': 15,
 'com.global.musvn': 3,
 'com.jsjssea.google': 3,
 'dev.song.kiem.loan.vu': 3,
 'dev.songkiem.loanvu': 3,
 'vn.funtap.tinhkiem.mobile3d': 3,
 'vn.funtap.tqvuonggia': 3,
 'com.lilithgames.themirror.gp': 3,
 'gsn.zps.ccn': 15,
 'com.farlightgames.samo.gp.vn': 3,
 'com.prty.hpz': 3,
 'vn.funtap.tamquoctruyenky': 3,
 'com.garena.game.kgsam': 15,
 'com.garena.game.kgth': 15,
 'com.garena.game.kgtw': 15,
 'com.garena.game.kgvn': 15,
 'vng.games.boom.together': 15,
 'com.garena.game.fo4mvn': 15,
 'congthanh.xungde.mobi.dev': 3,
 'gsn.game.binhnew': 20,
 'gsn.game.capsaSusun': 20,
 'gsn.game.tienlenNew': 20,
 'gsn.game.tienlennew': 20,
 'gsn.game.zingplaynew1': 15,
 'gsn.game.zingplaynew2': 15,
 'com.global.pnckvn': 3,
 'com.mxdzz.sea': 3,
 'com.garena.game.kofvn': 15,
 'vn.vplay.qaphl1.t023a': 3,
 'com.overseas.daqing1': 3,
 'vgp.dung.gia.dai.luc': 3,
 'com.lilithgame.roc.gp': 3,
 'com.lilithgames.rok.gp.jp': 3,
 'com.lilithgames.rok.gpkr': 3,
 'com.rok.gp.vn': 3,
 'com.vng.onepunchman': 15,
 'vng.games.revelation.mobile': 15,
 'com.global.dl3dft.gp': 3,
 'vn.funtap.gardenbattle': 3,
 'com.g2us.armedwarriors.vietnamchannel1': 15,
 'com.g2us.armedwarriors.vietnamgoogle': 15,
 'vnggame.anhhungchienhon.armedwarriors': 15,

In [43]:
factor = revenue_factor_by_app.get("abx")

In [45]:
factor == None

True

In [28]:
df_app_full_info_adjusted

,app_id,canonical_country,name,publisher_name,publisher_id,humanized_name,icon_url,os,active,url,...,screenshot_urls,tablet_screenshot_urls,description,subtitle,promo_text,permissions,supported_languages,country_release_date,cleaned_publisher_name,revenue_multiplier
0,336834650,US,Moorhuhn Deluxe!,Acmee GmbH,330311834,Moorhuhn Deluxe!,https://is1-ssl.mzstatic.com/image/thumb/Purpl...,ios,False,https://apps.apple.com/US/app/id336834650?l=en,...,['https://is3-ssl.mzstatic.com/image/thumb/Pur...,['https://is3-ssl.mzstatic.com/image/thumb/Pur...,"In this hunting game for iPhone, iPad and iPod...",Crazy Chicken,NaN,NaN,"['en', 'fr', 'de', 'it', 'es']",2009-11-03T08:00:00Z,NaN,1
1,373942073,US,Real Solitaire for iPad,"EdgeRift, Inc.",292786128,Real Solitaire,https://is1-ssl.mzstatic.com/image/thumb/Purpl...,ios,True,https://apps.apple.com/US/app/id373942073?l=en,...,[],[],Play the best new free Solitaire! Millions of ...,Classic Solitaire puzzle game.,NaN,NaN,['en'],2010-06-18T00:00:00Z,NaN,1
2,457859877,US,Kick it out! Football Manager,Ludetis UG,457859880,Kick it out! Football Manager,https://is2-ssl.mzstatic.com/image/thumb/Purpl...,ios,False,https://apps.apple.com/US/app/id457859877?l=en,...,['https://is1-ssl.mzstatic.com/image/thumb/Pur...,[],Football is emotion - and Kick it out! is the ...,NaN,NaN,NaN,"['bg', 'nl', 'en', 'fr', 'de', 'el', 'it', 'pl...",2012-05-10T00:39:29Z,NaN,1
3,472626879,US,Coin Hunter 2,Easeware,448134626,Coin Hunter 2,https://is2-ssl.mzstatic.com/image/thumb/Purpl...,ios,True,https://apps.apple.com/US/app/id472626879?l=en,...,['https://is1-ssl.mzstatic.com/image/thumb/Pur...,[],"By the leads of the map father left, the brave...",NaN,NaN,NaN,['en'],2011-10-19T05:14:22Z,NaN,1
4,472885640,US,JJ斗地主-欢乐棋牌休闲合集,JJWorld(Beijing) Network Technology Company Li...,472885643,JJ斗地主-欢乐棋牌休闲合集,https://is1-ssl.mzstatic.com/image/thumb/Purpl...,ios,True,https://apps.apple.com/US/app/id472885640?l=en,...,['https://is1-ssl.mzstatic.com/image/thumb/Pur...,[],JJ斗地主牌局专业，赛制公平，无猪队友，无作弊，斗得过瘾，赢得畅快。24小时比赛不间断，回馈...,数亿玩家的口碑之选,NaN,NaN,[],2012-02-29T00:00:00Z,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80475,onetap.game.lines98.codien,US,Lines 98 Cổ Điển,ONETAP,ONETAP,Lines 98 Cổ Điển,https://play-lh.googleusercontent.com/whs8Io-c...,android,False,https://play.google.com/store/apps/details?hl=...,...,['https://play-lh.googleusercontent.com/r15UVV...,[],Lines 98 cổ điển dành cho những ai yêu thích t...,NaN,NaN,{'Wi-Fi connection information': ['view Wi-Fi ...,[],2022-05-12T00:00:00Z,NaN,1
80476,se.illusionlabs.bmx,US,Touchgrind BMX,Illusion Labs,Illusion+Labs,Touchgrind BMX,https://play-lh.googleusercontent.com/OphBEeHx...,android,True,https://play.google.com/store/apps/details?hl=...,...,['https://play-lh.googleusercontent.com/YgNp3k...,[],Become a BMX pro and perform spectacular trick...,NaN,NaN,"{'Other': ['view network connections', 'full n...",[],2014-09-12T00:00:00Z,NaN,1
80477,sk.sivak.eldritchhorror.android,US,Ancient Terror: Lovecraftian S,Pixel Art Battles,Pixel+Art+Battles,Ancient Terror,https://play-lh.googleusercontent.com/v2d5kJN8...,android,False,https://play.google.com/store/apps/details?hl=...,...,['https://play-lh.googleusercontent.com/oSqasN...,[],PC version: https://ancientterror.itch.io/anci...,NaN,NaN,{'Photos/Media/Files': ['read the contents of ...,[],2019-03-29T00:00:00Z,NaN,1
80478,word.hunt.connect,US,Word Hunt: Word Puzzle Game,Word Search Games,Word+Search+Games,Word Hunt: Word Puzzle Game,https://play-lh.googleusercontent.com/je-v1alA...,android,True,https://play.google.com/store/apps/details?hl=...,...,['https://play-lh.googleusercontent.com/P27Txm...,[],"Play Word Hunt 9 mins a day, search the words,...",NaN,NaN,{'Wi-Fi connection information': ['view Wi-Fi ...,[],2019-08-09T00:00:00Z,NaN,1
80479,world.playme.x,US,Alien Survivor: Survival Arena,PlayMe Studio,PlayMe+Studio,Alien Survivor,https://play-lh.googleusercontent.com/yl_rSV3_...,android,True,https://play.google.com/store/apps/details?hl=...,...,['https://play-lh.googleusercontent.com/RUn0WW...,[],Embark on a thrilling journey in the role of a...,NaN,NaN,{'Wi-Fi connection information': ['view Wi-Fi ...,[],2023-07-21T00:00:00Z,NaN,1

In [31]:
# Get the list of Apps requiring revenue adjustment and their multipliers
df_app_and_revenue_multiplier = df_app_full_info_adjusted[df_app_full_info_adjusted['revenue_multiplier']!=1][['app_id','revenue_multiplier']]

In [33]:
for app_id in df_app_and_revenue_multiplier['app_id']:
    print(app_id)

6476554439
904890205
1521771561
1621483610
6443442131
6740561197
6740611773
6747331870
1431610213
6504474986
6451137140
1127157068
1159236542
1261834568
1577123983
1438376417
1469164964
6466761725
6479692189
1583717977
6747154050
6444060858
1591546813
1588009371
6448143057
6717587690
6740536674
799319182
887752917
1528287521
6633416904
1573033171
1495625837
6446198142
1616630100
6499431484
1665137451
6478189835
6479636678
6476176288
1521411821
6467690444
6478138913
638689075
6480434384
6446388135
6451463643
1546606867
6738641269
1460786661
1633945760
6478901170
6504267531
1071744151
1593143999
1502412815
1467842750
1521779642
1582020814
6479231049
6446610044
1417141579
1444754600
1464689103
1587704770
6737103277
1559698151
1465097065
6453690496
1306451576
6471930550
1453657959
6472704324
6469768541
1501476139
1635925350
1477780217
6449825814
1632354684
6448864292
6502928253
1489436528
1546353393
6456407206
6502480712
6596734272
6480383911
6443444765
1451281983
1570594577
1472743924
6738091256
6480404570
1448024270
1616610297
1620319514
6444932771
6480410032
1438493375
6446750210
1518968894
6449966646
1569151989
1633394133
1300146617
1480516829
6474838818
1612175933
1670791259
6468433525
6738572450
6470252900
6443668820
6461417156
1455953893
6466396468
6742647964
1531280382
6475714083
6738905182
1672472869
6447612680
6737220373
1583880258
1547396989
1414804192
1446390036
1612001355
6742177455
1156810287
1202529338
1221871390
6448143284
6742437694
1515449050
1438396625
1012864419
6736925794
1434052677
6448943160
6478959083
1052983610
1453469177
6550905396
1281535229
942043135
1474935601
1634389457
1416604843
1435297178
1464658787
1514341641
1557176966
1590154620
1579889775
6740482237
1495055713
1549824326
1607282320
6472133989
6499399033
1370300345
6738371242
1596859213
6450526727
1199882006
6743202626
1483753846
6480037958
1547943736
554597348
562989701
578250301
578252579
6443998295
6745683002
6736819155
6475273991
1230292637
1581941519
1593573796
6544794058
1450238838
1537216540
1585602211
1098189387
1610291670
6447750572
6514312909
6475273921
1197441484
6443462521
1491703061
6474715805
1520159653
1529414550
1533615861
6447841794
1619055583
1439862260
1560124228
1570746506
6498472624
1498402668
1125893746
1485542024
6738274677
6443760593
1523256630
6476652682
6748971774
1509373363
6446679128
1372629721
1418864900
1428316113
1441600774
1465849529
1501618516
1501619128
1504586985
1504587645
1439414645
1477800522
6670604287
6738761685
6739530152
963664008
996809719
1118620009
1578623489
1641642655
1376515087
1464502423
1516465879
6739119850
1610048857
6737467132
6448320673
1645497690
6450761748
1207998539
1068204657
6479236752
6479175676
6475951069
1619055257
6448333104
6480329405
1358604343
6472019436
6474231541
6446393713
1572417749
1624412609
908192673
1058728157
1545808948
6463065706
6504342170
1546174938
1613851348
1217791326
6476137851
1504054504
1632874166
1522842979
6467398199
1541275013
1637396239
6480159278
1562608318
6445982244
6502498607
1642861858
1643854223
6478273595
6739808002
6743733953
1610703929
1287508973
1619722656
6504784958
1523281185
6450900363
6479681223
6478090188
6744964055
6590610850
6466970768
6505037845
6742124069
1599056590
1638876595
1441417054
950176941
6451477469
1297293884
1624503075
1132499977
1174766451
1505731053
1502971131
1613648368
403710610
426911698
456887491
463695183
467044485
467046915
467589706
473917756
473920065
574769161
574771160
664467619
664575829
708986361
725437153
1539383751
1521236603
6749760949
1541992176
6462862543
1208729802
1570767171
6599836402
1577970257
6448781122
1141358828
6478379359
1531825274
1479050948
1479281298
6480159814
406889139
6450002245
1447933800
1621098895
1531831962
6742780202
1436932265
1505720247
1277551859
6740510300
6449674450
1089079153
1150288115
1150331854
1150337432
1427128108
1427414541
6475763562
894956701
908617867
6446672928
6473259128
6502440184
1078191559
6745806781
1015763729
1558779269
1574489575
1589886973
6740690310
6477903252
6738380021
1051206681
1073852575
1393015117
1488431275
964827011
6443894073
6504058743
6451180763
1568659894
1578835721
1195621598
6504593009
6596747799
1070492711
1261675692
1463369328
6503333670
993081569
1017635295
1023316377
1058716053
6575363756
6739763390
1463380174
1577149017
6471364763
6450447751
1428475506
6468942281
1618158368
6738688188
1471932438
1638086822
6737226348
1572615571
6453691541
6478485058
1313204995
6502153297
1642487048
445297616
853000739
1236412425
1507180749
1496612433
6446024007
6738161495
1607048270
6450411268
6473467482
1470911692
6478997449
6738500946
553834731
1436138195
1040134392
1105855019
1465688043
1477030970
1238026766
1478858105
1451307336
6739480917
1172124096
1492680134
1588665666
1072032563
1091188714
1104555626
6467180067
6612015169
6743143064
1602460179
1127240206
1663702161
1565125572
6450451786
1604207548
vn.linh.kiem.chi.mong
com.global.antgamevn
com.vn.sl.google
gsn.game.talanew
gsn.game.talanew3
gsn.game.zingplaynew3
gsn.game.zingplaytala
com.xxyx.sea
com.xxyx.vn
com.allstarunion.myths.vn
com.iccgame.grail
com.readygo.dark.gphh
au2.audition.vtcgame.dancing.aumobile.gamethoitrang
ship.simulator.river.climb
sea.reignofwarlords
com.nekki.shadowfight2.paid
com.vtcmobile.longchien
com.vtcmobilejsc.phuckichvtc
com.gmt.huntersaga.gamota
vnggames.tqts.mmo.vn
com.jwsvn.gg
com.more.lastfortress.gpvn
com.vtcmobile.thanhkiemluanhoi
com.zps.caro
com.lilithgames.wgame.android.jp
com.lilithgames.wgame.android.kr
com.wondergames.warpath.gp
com.wondergames.warpath.gp.ptr
com.allstarunion.ta.vn
com.zzsj.vn
vgp.dev.thanh.van.kiem
vn.kvtm.js
vn.kvtm.khuvuontrenmay
com.gosu.cuuduong2
vn.vplay.huyentuong.t021a
vng.games.kiemvu.phong.idle.rpg
com.gsn.zps.full
com.vng.lineage2mvn
gsn.game.zingplaynew
shooter.online.warplanes
com.sgyml.vn.an
gsn.zps.thoiloan
com.vntth.sgzzlb.gp.vn
rail.road.tycoon
com.nobodyshot.POLYWAR
vn.funtap.tannhatkiem
vn.funtap.thucsonthienhachien
vn.vplay.khoinguyen.t016a
com.vtc.tt11
com.archosaur.vn.dr.gp
com.shg.sg416
vn.dev.thienvu.thanvuong
com.playrix.township
vn.huyenthoaing.gg
com.tg.yls.vn
vn.gosu.atomarena
com.riotgames.league.teamfighttacticsvn
vn.pg1.vltk1m
com.azurinteractive.StarForces
com.global.byvn.google
vn.funtap.kiemma3d
com.camelgames.superking
com.mechanist.poi.vn
thelegendofneverland.thelegend.neverland.openworld.gamehay.trochoi.vtc.game
vng.games.gs1.phongthan.mobile.com
vng.games.taydu.ngokhong.idle.rpg
com.vtcmobile.hcm.g170801.vqtm
com.vtcmobile.phongvanchivtc
gsn.tdf.vn
vn.funtap.daihieptaptap
com.azurgames.dinosaurs
com.MelsoftGames.FamilyIslandFarm
com.funtap.thienkiemmobile
train.railroad.climb.simulator
com.global.aoempiresvn
vng.games.tamquoc.idle.rpg
and.onemt.boe.vi.appota
com.camelgames.ig
com.lilithgame.isoland2.gp.mf
com.lilithgame.isoland2.gpen
vn.funtap.danhtuong.truyenky
dev.manga.bachay
gamebongda.bongda.vuabongda.football.kingoffootball.trochoi.mienphi.game.online.vtc
com.gs2.ttl3dmb
com.mobilegame.mn12
com.shg.sg401new
com.gmt.tamquoc.lienthanhchien
com.vtcmobile.autop
com.gosu.cdtc
com.papegames.nn4.vn
com.miHoYo.bh3oversea_vn
com.vtcmobile.wows
vng.games.mu.webzen.online
com.vng.psvkcvn
dev.vgp.yeu.linh.gioi
vn.vgpjsc.dauhonsu
com.snmjglo.google
vn.gosu.nhatdaithienton
com.redriver.shjjc
pocket.tales
com.pocket.shooter
com.redriver.gp.vi.lzgwy
com.shg.sg381
com.more.dayzsurvival.gpvn
com.redtailworks.slimetd
com.szckhd.jwgly.azkr
com.szckhd.jwgly.azvn
vng.games.thienlong.kiemhiep3d.mobile
com.hxmjl.vn.an
com.elex.twdsaw.vn
com.igg.android.castleclashvn
com.camelgames.wod
vng.games.taydu.chienthuat.online
com.onemt.and.kc.vn
com.shg.sg336
com.dts.freefiremax
com.dts.freefireth
com.vnggames.ghoststory
com.vng.playtogether
com.vtcfun.fun.cardgame.boardgame.vtc
vng.games.my.cafe.hello.coffee
com.shg.sg280
com.shg.sg434
com.shg.sg434new
com.global.dqvn
com.allstarunion.beastlord.vn
com.vtc.tapkich
com.zps.spfvn
com.playrix.manormatters
vn.vplay.vohiep.t027a
com.gmt.lucdaoluanhoi
com.riotgames.league.wildriftvn
com.vtcmobile.dragonheroes
com.vtcmobile.mn16
com.Lilith.Abi
vn.vplay.dauthantuyetthe.t010a
com.shg.sg391
vn.dev.ma.kiem.vo.song
com.vng.hpqtvn
vng.game.sky.fantasy.song.vn
com.hhgame.mcggvn
com.vtcmobile.xcity
vn.tamgioi.anhhung
vn.vplay.tamquocchi.t025a
com.vng.pubgmobile
com.vng.thieunien3qvng
com.garena.game.westtw
com.fun.lastwar.vn.gp
ru.azurinteractive.robotwarfare
com.dinhphong2.gg
vn.funtap.chuyensinh
com.herogames.crisisaction
com.zps.cotyphu.af
com.gamedevltd.wwh
com.angame.ddtank.vn
com.angame.gunnymobi.vn
com.angame.mwork.vn
com.gmt.hoathienkiepgamota
com.eoc.google.watt
com.garena.game.fcsac
com.garena.game.fctw
com.vng.speedvn
com.vtcmobile.thk
com.dc.gok.google
com.shg.sg328
com.archosaur.vn.sgzgc.gp
com.world.war.defence
com.alphainteractive.sniperawpshooter
roe.vn.riseofempires
com.archosaur.vn.yslzm.gp
com.silkroad.mb
vn.funtap.phuonghoang.camtu
com.lin2vn
com.zjws.sea.vn
com.topwar.gp.vn
com.vng.thiennhaiminhnguyetdaovng
com.playrix.wildscapes_new.google
com.playrix.zoo_m3.gplay
com.tg.dpcq2.vn
com.vtcmobile.phongmachien
vn.dev.tuma.truyenky
com.mobi389.murom
com.nekki.vector
com.nekki.vector.paid
com.vtcmobile.ghbp
zps.games.bida3d.vn
com.pergame.starliteden
com.pergame.starlitedenru
com.ddup.zombiewaves.zw.vn
vn.vgpjsc.langvan.chikiem
com.gmt.trutien
com.ptct.gp.vn
com.slsm.an.en
com.slsmus.an.watt
com.com2us.smon.normal.freefull.google.vn.android.common
com.nekki.ninjaparty
com.tg.ysr.vn
com.vizorapps.mahjong
com.vtcmobile.thaicophong
vnggames.gs1.volam3
vn.thuongkhungchikiem.funtap
com.igg.android.vikingrisevn
com.gamedevltd.modernstrike
com.m3.vn
com.lilithgame.hgame.gp
com.lilithgame.hgame.gp.jp
com.lilithgame.hgame.gp.kr
com.lilithgames.hgame.gp.id
vn.funtap.tuyetthevolam
com.roblox.client.vnggames
com.funtapgame.kart.rushplus.kartm
com.igg.android.doomsdaylastsurvivorsvn
com.vng.fwvn
com.aladinfun.piggytravel.android.vietnam
com.vtc.tco
com.exoticmatch.game
com.gs2.mua
com.shgame.sg326
game.bida.vng
com.vtcmobile.lienminhstickman
com.gmt.kiemthanfinalfantasy
com.jsjsvn.google
com.vng.vltkm
com.shg.sg433
com.ddup.zombiewaves.zw
com.ddup.zombiewaves.zw.ru
com.mobigame.qjxx
com.vng.mf.liteuamo
com.oasis.immortal
com.and.vn.daqin
com.shg.sg295
vng.games.thienlong.tlbb3d.kiemhiep
dev.phong.van.kiem
com.wod.ag.global
com.vtcmobile.tramtienquyetobb
com.wsy.google.hk.wansuiye
com.wsy.google.wansuiye
com.wsy.google.wansuiye.en
com.wsy.google.wansuiye.fr
com.wsy.google.wansuiye.id
com.wsy.google.wansuiye.jp
com.wsy.google.wansuiye.kr
com.wsy.google.wansuiye.ru
com.wsy.google.wansuiye.th
com.igg.android.mobileroyalevn
vn.pp.dt3q
com.garena.game.df
com.tkc.an.funiverse
vn.vplay.chuongmon.t022a
vn.zps.tl2
air.com.limboworks.honorofcup.appota.sea
com.gmt.tamquoc.gamota
com.camelgames.aoz
com.camelgames.aoz.arabic
com.soha.evony
com.kingsgroup.sos.vn
com.vtcmobile.hoasonkiemthe
vn.vplay.chiengioi4d.t002a
com.iccgame.silkroadonline.androidvn
com.shgame.sg314
vn.funtap.daitienminhdidauthe
com.vtcmobile.talachienthan
com.garena.game.caithetranhhung
com.vtcmobile.aumobilevtc
com.zlya.sabuk
com.allstarunion.wow.vn
com.shg.sg292
com.melesta.coffeeshop
com.rapidfiregames.backpackbrawl
vn.funtap.dauphamobile
com.ddj.vn
vn.dev.hiepkhach.chica
vn.dev.thuc.than.ky
com.gmt.hiepkhachgiangho
com.gp.we
com.vng.mf.uamo
com.vtcmobile.mn09
ufc.sieusaobongda.bongda.sieusao.fifa.game.thethao.online.vtc.game
com.gp.lttq
com.giant.supersus
com.je.supersus
com.mobigame.tt12
com.huyenthoai.hvht
com.play.rosea
com.vng.tanngoalong
com.wzlr.sea
vn.zalo.ngoalongmb
com.mobigame.cuongma2
com.nekki.shadowfight
com.nekki.shadowfighttv
com.dieselpuppet.detectivestory
com.funtap.vtqvn
com.HoYoverse.NapVn
com.gsn.newca
com.tjb.an.en4399
com.zingplay.cabeo
zps.myfish.vn
com.vtcmobile.chienthankynguyen
com.vtcmobile.ctkn
com.vtc.nguthansu
com.global.frxxvn
com.gosu.gamo.hogiachunhan
com.hh.xherovn.moblie
com.mrtgd.sea
com.vtcmobile.qslm
vnggames.topeleven.football.soccermanager
com.seaofconquest.googlevn
com.vtcmobile.tayduky
com.gmt.anhhungxadieu
vn.vplay.lienminhphapsu.a1
com.netease.g78na.vn
com.shg.sg426
com.vtc.tlvd
offroad.racing.game
vn.funtap.kynuhoangcung
com.shg.sg438
vn.vplay.tamquocdailuc.t019a
com.netease.newspikevn
vn.vplay.kiemlai.t024a
rts.bunker.wars
vng.games.dream.mobile
dev.ngulong.kiem3d
com.vng.gpdttkvn
com.vng.tinhvan.dota
us.kick9.k3000000013.c3101000001
com.miHoYo.GenshinImpact.vn
com.Nobodyshot.kuboom
com.gmt.tienkiemkyduyen3d
com.nekki.shadowfight.shades
com.gmt.dolong3d
com.gmt.ythien
com.riotgames.legendsofruneterravn
vnggames.volam.kiemthe.origin
com.playrix.fishdomdd.gplay
io.randomco.travel
com.BastardGames.HiredHeroesMedievalWarfare
com.vng.tanomg3q
com.daichien.mobile
com.vtcmobile.daichienfull
com.dragon.sails
com.global.ztmslgvn
vn.gosu.cuuam2d
puzzle.merge.hotel.empire
vn.dev.mongkiem.tieudao
com.tg.jsxw.vn
com.zillionwhales.mushroomwars2
vn.gosu.cuuam
com.nekki.shadowfightarena
com.rxsj.an.en4399
com.gsn.getmoney
com.moonactive.coinmaster
com.yuewan.tgvn
com.gmt.thankhucmobile
com.vng.metalslug.rambolun
com.global.musvn
com.jsjssea.google
dev.song.kiem.loan.vu
dev.songkiem.loanvu
vn.funtap.tinhkiem.mobile3d
vn.funtap.tqvuonggia
com.lilithgames.themirror.gp
gsn.zps.ccn
com.farlightgames.samo.gp.vn
com.prty.hpz
vn.funtap.tamquoctruyenky
com.garena.game.kgsam
com.garena.game.kgth
com.garena.game.kgtw
com.garena.game.kgvn
vng.games.boom.together
com.garena.game.fo4mvn
congthanh.xungde.mobi.dev
gsn.game.binhnew
gsn.game.capsaSusun
gsn.game.tienlenNew
gsn.game.tienlennew
gsn.game.zingplaynew1
gsn.game.zingplaynew2
com.global.pnckvn
com.mxdzz.sea
com.garena.game.kofvn
vn.vplay.qaphl1.t023a
com.overseas.daqing1
vgp.dung.gia.dai.luc
com.lilithgame.roc.gp
com.lilithgames.rok.gp.jp
com.lilithgames.rok.gpkr
com.rok.gp.vn
com.vng.onepunchman
vng.games.revelation.mobile
com.global.dl3dft.gp
vn.funtap.gardenbattle
com.g2us.armedwarriors.vietnamchannel1
com.g2us.armedwarriors.vietnamgoogle
vnggame.anhhungchienhon.armedwarriors
com.lilithgame.sgame.gp.jp
com.zps.ctp2
com.shg.sg435
com.vng.ngoisaothoitrang
com.gamedevltd.destinywarfare
com.playrix.farmscapes
com.bfa.battlelines
com.nekki.shadowfight3
com.vng.tlbb3dm.vn
vn.dev.longhon.kynguyen
lokapala.vtcgame.moba
com.twincorp.bancaonline
com.vtcmobile.daosixuatquan
com.playrix.homescapes
com.mechanist.vampire.aos.vn
com.shg.sg423
com.vizorinteractive.zombiesettlersv2
com.and.riseofthekingsvn
com.wyd.gunpow
com.garena.game.ak47en
com.garena.game.ak47th
com.garena.game.ak47tw
com.garena.game.headvn
com.greenmushroom.boomblitz.gp.vn
com.vtcmobile.gz05
com.azurgames.sailships
com.vizorapps.roadtrip
com.gmt.amtt
com.playrix.mysterymatters
com.hhgame.mlbbvn
com.vng.mlbbvn
com.vng.remementowhiteshadow
com.vtcmobile.thienkhoi
com.garena.game.fcmobilevn
com.igg.android.lordsmobilevn
com.valorlegend.vn
vn.funtap.tamquocx
vng.game.gunny.mobi.classic.original
com.vtc.mn15
com.nekki.mobile11x11new
vn.vplhn.game.thanma.a2
com.azurgames.skycombat
com.playrix.fishdom_solitaire.gplay
com.vtcmobile.project9
chess.gsn.portalnew
com.fruitshake.fairyrpg
com.gsn.zpb
gsn.zingplay.cotuong
gsn.zingplay.cotuong.zoom
com.vizorapps.atlantis
com.emagroups.coi
com.shg.sg394
vn.dzogame.hkm
vn.vgp.kiem.khach.phong.lang
vn.shg.sg306
vng.games.tamquochuyentuong3q
com.king.candycrushsaga
puzzle.merge.adventure
vn.funtap.nhatkiemgiangho
com.garena.game.codm
com.playrix.gardenscapes
com.vng.codmvn
com.gs2.omg
gsn.game.sam
com.dieselpuppet.hidden
com.gmt.vuabongdacs
com.star360mobi.hoangcung
com.azurgames.lastday
aubeatvtc.aubeat.audition.gamenhay.dance.nhay.au.vtc.game.vtcgame
com.tap4fun.ape.gplay.vn
com.mega.kh.kols
com.metime.movingtower
us.epic.magician
vn.funtap.kiemvu.hanhca
com.hhgame.mladventure
com.vizorapps.klondike
com.vtcmobile.Ultimatefootballmobile
com.vtcmobile.tqc
pool.us
com.glapp.solitaire
com.vtc.ghtyk

In [39]:
df_app_and_revenue_multiplier[df_app_and_revenue_multiplier['app_id']=='1573033171']['revenue_multiplier'].item()

3

In [ ]:
for app_id in df_app_and_revenue_multiplier['app_id']:
    print("Adjusting for aid: {}".format(app_id))
    for record in

In [40]:
app_performance_data

[{'aid': 336834650, 'cc': 'VN', 'd': '2014-01-13T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-17T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-19T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-22T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-28T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-29T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-02-13T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-03-01T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-03-12T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-13T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-19T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-22T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-27T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-04T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-06T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-07T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-08T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-09T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-11T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-16T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-17T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-20T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-23T00:00:00Z', 'ir': 34},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-24T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-27T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-31T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-01T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-03T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-05T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-06T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-07T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-09T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-10T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-11T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-12T00:00:00Z', 'ir': 23},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-13T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-14T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-15T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-16T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-17T00:00:00Z', 'ir': 55},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-18T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-19T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-22T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-23T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-25T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-26T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-27T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-28T00:00:00Z', 'ir': 58},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-30T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-31T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-03T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-04T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-05T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-06T00:00:00Z', 'ir': 45},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-07T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-08T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-09T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-10T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-11T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-12T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-13T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-14T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-16T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-17T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-20T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-23T00:00:00Z', 'ir': 12},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-24T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-25T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-26T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-27T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-28T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-29T00:00:00Z', 'ir': 12},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-30T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-01T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-02T00:00:00Z', 'ir': 56},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-03T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-04T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-05T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-06T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-08T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-10T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-11T00:00:00Z', 'ir': 27},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-12T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-14T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-15T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-16T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-17T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-18T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-19T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-20T00:00:00Z', 'ir': 40},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-21T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-24T00:00:00Z', 'ir': 45},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-25T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-26T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-27T00:00:00Z', 'ir': 57},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-28T00:00:00Z', 'ir': 54},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-29T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-30T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-01T00:00:00Z', 'ir': 54},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-02T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-03T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-04T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-05T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-06T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-07T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-08T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-10T00:00:00Z', 'ir': 39},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-11T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-13T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-14T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-15T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-17T00:00:00Z', 'ir': 149},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-18T00:00:00Z', 'ir': 68},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-20T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-21T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-24T00:00:00Z', 'ir': 46},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-27T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-01T00:00:00Z', 'ir': 47},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-03T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-06T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-08T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-10T00:00:00Z', 'ir': 12},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-11T00:00:00Z', 'ir': 13},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-17T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-18T00:00:00Z', 'ir': 112},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-19T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-20T00:00:00Z', 'ir': 25},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-22T00:00:00Z', 'ir': 93},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-24T00:00:00Z', 'ir': 61},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-25T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-28T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-30T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-31T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-01T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-02T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-03T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-05T00:00:00Z', 'ir': 73},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-06T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-07T00:00:00Z', 'ir': 24},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-09T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-10T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-11T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-12T00:00:00Z', 'ir': 22},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-13T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-14T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-16T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-17T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-19T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-22T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-23T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-24T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-25T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-26T00:00:00Z', 'ir': 69},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-27T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-28T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-29T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-30T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-31T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-01T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-02T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-03T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-04T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-05T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-06T00:00:00Z', 'ir': 45},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-07T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-08T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-09T00:00:00Z', 'ir': 65},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-10T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-11T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-12T00:00:00Z', 'ir': 52},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-13T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-14T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-15T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-16T00:00:00Z', 'ir': 51},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-17T00:00:00Z', 'ir': 50},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-18T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-19T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-20T00:00:00Z', 'ir': 40},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-21T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-22T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-23T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-24T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-26T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-27T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-28T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-01T00:00:00Z', 'ir': 56},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-02T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-03T00:00:00Z', 'ir': 18},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-04T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-05T00:00:00Z', 'ir': 66},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-06T00:00:00Z', 'ir': 83},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-07T00:00:00Z', 'ir': 47},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-08T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-09T00:00:00Z', 'ir': 17},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-10T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-11T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-12T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-13T00:00:00Z', 'ir': 36},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-14T00:00:00Z', 'ir': 58},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-15T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-16T00:00:00Z', 'ir': 35},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-17T00:00:00Z', 'ir': 132},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-18T00:00:00Z', 'ir': 33},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-19T00:00:00Z', 'ir': 66},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-20T00:00:00Z', 'ir': 13},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-21T00:00:00Z', 'ir': 147},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-22T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-23T00:00:00Z', 'ir': 84},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-24T00:00:00Z', 'ir': 44},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-25T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-26T00:00:00Z', 'ir': 23},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-27T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-28T00:00:00Z', 'ir': 41},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-29T00:00:00Z', 'ir': 36},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-30T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-31T00:00:00Z', 'ir': 34},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-01T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-02T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-03T00:00:00Z', 'ir': 97},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-04T00:00:00Z', 'ir': 52},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-05T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-06T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-07T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-08T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-09T00:00:00Z', 'ir': 110},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-10T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-11T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-12T00:00:00Z', 'ir': 96},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-13T00:00:00Z', 'ir': 58},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-14T00:00:00Z', 'ir': 11},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-15T00:00:00Z', 'ir': 49},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-16T00:00:00Z', 'ir': 68},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-17T00:00:00Z', 'ir': 38},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-18T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-19T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-20T00:00:00Z', 'ir': 37},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-21T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-22T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-23T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-24T00:00:00Z', 'ir': 111},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-25T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-26T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-27T00:00:00Z', 'ir': 63},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-28T00:00:00Z', 'ir': 69},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-29T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-30T00:00:00Z', 'ir': 125},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-01T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-02T00:00:00Z', 'ir': 11},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-03T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-04T00:00:00Z', 'ir': 23},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-05T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-06T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-07T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-08T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-09T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-10T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-11T00:00:00Z', 'ir': 128},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-12T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-13T00:00:00Z', 'ir': 33},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-14T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-15T00:00:00Z', 'ir': 37},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-16T00:00:00Z', 'ir': 43},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-17T00:00:00Z', 'ir': 91},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-18T00:00:00Z', 'ir': 263},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-19T00:00:00Z', 'ir': 103},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-20T00:00:00Z', 'ir': 89},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-21T00:00:00Z', 'ir': 112},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-22T00:00:00Z', 'ir': 65},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-23T00:00:00Z', 'ir': 139},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-24T00:00:00Z', 'ir': 38},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-25T00:00:00Z', 'ir': 255},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-26T00:00:00Z', 'ir': 33},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-27T00:00:00Z', 'ir': 44},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-28T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-29T00:00:00Z', 'ir': 64},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-30T00:00:00Z', 'ir': 42},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-31T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-01T00:00:00Z', 'ir': 54},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-02T00:00:00Z', 'ir': 68},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-03T00:00:00Z', 'ir': 17},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-04T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-05T00:00:00Z', 'ir': 23},

# Modeling Layer

In [9]:
# read data from json
with open('data/draft/app_performance_data_1764146538.json', 'r') as file:
    app_performance_data = json.load(file)

In [20]:
app_performance_data

[{'aid': 336834650, 'cc': 'VN', 'd': '2014-01-13T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-17T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-19T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-22T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-28T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-01-29T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-02-13T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-03-01T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-03-12T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-13T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-19T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-22T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-06-27T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-04T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-06T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-07T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-08T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-09T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-11T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-16T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-17T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-20T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-23T00:00:00Z', 'ir': 34},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-24T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-27T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-07-31T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-01T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-03T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-05T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-06T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-07T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-09T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-10T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-11T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-12T00:00:00Z', 'ir': 23},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-13T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-14T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-15T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-16T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-17T00:00:00Z', 'ir': 55},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-18T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-19T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-22T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-23T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-25T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-26T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-27T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-28T00:00:00Z', 'ir': 58},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-30T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-08-31T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-03T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-04T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-05T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-06T00:00:00Z', 'ir': 45},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-07T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-08T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-09T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-10T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-11T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-12T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-13T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-14T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-16T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-17T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-20T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-23T00:00:00Z', 'ir': 12},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-24T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-25T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-26T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-27T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-28T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-29T00:00:00Z', 'ir': 12},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-09-30T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-01T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-02T00:00:00Z', 'ir': 56},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-03T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-04T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-05T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-06T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-08T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-10T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-11T00:00:00Z', 'ir': 27},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-12T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-14T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-15T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-16T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-17T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-18T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-19T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-20T00:00:00Z', 'ir': 40},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-21T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-24T00:00:00Z', 'ir': 45},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-25T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-26T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-27T00:00:00Z', 'ir': 57},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-28T00:00:00Z', 'ir': 54},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-29T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-10-30T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-01T00:00:00Z', 'ir': 54},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-02T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-03T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-04T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-05T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-06T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-07T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-08T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-10T00:00:00Z', 'ir': 39},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-11T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-13T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-14T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-15T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-17T00:00:00Z', 'ir': 149},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-18T00:00:00Z', 'ir': 68},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-20T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-21T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-24T00:00:00Z', 'ir': 46},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-11-27T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-01T00:00:00Z', 'ir': 47},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-03T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-06T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-08T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-10T00:00:00Z', 'ir': 12},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-11T00:00:00Z', 'ir': 13},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-17T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-18T00:00:00Z', 'ir': 112},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-19T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-20T00:00:00Z', 'ir': 25},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-22T00:00:00Z', 'ir': 93},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-24T00:00:00Z', 'ir': 61},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-25T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-28T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-30T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2014-12-31T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-01T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-02T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-03T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-05T00:00:00Z', 'ir': 73},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-06T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-07T00:00:00Z', 'ir': 24},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-09T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-10T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-11T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-12T00:00:00Z', 'ir': 22},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-13T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-14T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-16T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-17T00:00:00Z', 'ir': 16},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-19T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-22T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-23T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-24T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-25T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-26T00:00:00Z', 'ir': 69},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-27T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-28T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-29T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-30T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-01-31T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-01T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-02T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-03T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-04T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-05T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-06T00:00:00Z', 'ir': 45},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-07T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-08T00:00:00Z', 'ir': 1},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-09T00:00:00Z', 'ir': 65},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-10T00:00:00Z', 'ir': 26},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-11T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-12T00:00:00Z', 'ir': 52},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-13T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-14T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-15T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-16T00:00:00Z', 'ir': 51},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-17T00:00:00Z', 'ir': 50},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-18T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-19T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-20T00:00:00Z', 'ir': 40},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-21T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-22T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-23T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-24T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-26T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-27T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-02-28T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-01T00:00:00Z', 'ir': 56},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-02T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-03T00:00:00Z', 'ir': 18},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-04T00:00:00Z'},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-05T00:00:00Z', 'ir': 66},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-06T00:00:00Z', 'ir': 83},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-07T00:00:00Z', 'ir': 47},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-08T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-09T00:00:00Z', 'ir': 17},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-10T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-11T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-12T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-13T00:00:00Z', 'ir': 36},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-14T00:00:00Z', 'ir': 58},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-15T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-16T00:00:00Z', 'ir': 35},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-17T00:00:00Z', 'ir': 132},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-18T00:00:00Z', 'ir': 33},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-19T00:00:00Z', 'ir': 66},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-20T00:00:00Z', 'ir': 13},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-21T00:00:00Z', 'ir': 147},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-22T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-23T00:00:00Z', 'ir': 84},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-24T00:00:00Z', 'ir': 44},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-25T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-26T00:00:00Z', 'ir': 23},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-27T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-28T00:00:00Z', 'ir': 41},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-29T00:00:00Z', 'ir': 36},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-30T00:00:00Z', 'ir': 21},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-03-31T00:00:00Z', 'ir': 34},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-01T00:00:00Z', 'ir': 2},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-02T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-03T00:00:00Z', 'ir': 97},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-04T00:00:00Z', 'ir': 52},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-05T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-06T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-07T00:00:00Z', 'ir': 29},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-08T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-09T00:00:00Z', 'ir': 110},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-10T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-11T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-12T00:00:00Z', 'ir': 96},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-13T00:00:00Z', 'ir': 58},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-14T00:00:00Z', 'ir': 11},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-15T00:00:00Z', 'ir': 49},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-16T00:00:00Z', 'ir': 68},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-17T00:00:00Z', 'ir': 38},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-18T00:00:00Z', 'ir': 32},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-19T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-20T00:00:00Z', 'ir': 37},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-21T00:00:00Z', 'ir': 5},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-22T00:00:00Z', 'ir': 3},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-23T00:00:00Z', 'ir': 7},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-24T00:00:00Z', 'ir': 111},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-25T00:00:00Z', 'ir': 6},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-26T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-27T00:00:00Z', 'ir': 63},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-28T00:00:00Z', 'ir': 69},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-29T00:00:00Z', 'ir': 10},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-04-30T00:00:00Z', 'ir': 125},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-01T00:00:00Z', 'ir': 8},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-02T00:00:00Z', 'ir': 11},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-03T00:00:00Z', 'ir': 4},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-04T00:00:00Z', 'ir': 23},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-05T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-06T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-07T00:00:00Z', 'ir': 9},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-08T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-09T00:00:00Z', 'ir': 48},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-10T00:00:00Z', 'ir': 31},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-11T00:00:00Z', 'ir': 128},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-12T00:00:00Z', 'ir': 28},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-13T00:00:00Z', 'ir': 33},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-14T00:00:00Z', 'ir': 20},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-15T00:00:00Z', 'ir': 37},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-16T00:00:00Z', 'ir': 43},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-17T00:00:00Z', 'ir': 91},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-18T00:00:00Z', 'ir': 263},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-19T00:00:00Z', 'ir': 103},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-20T00:00:00Z', 'ir': 89},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-21T00:00:00Z', 'ir': 112},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-22T00:00:00Z', 'ir': 65},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-23T00:00:00Z', 'ir': 139},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-24T00:00:00Z', 'ir': 38},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-25T00:00:00Z', 'ir': 255},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-26T00:00:00Z', 'ir': 33},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-27T00:00:00Z', 'ir': 44},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-28T00:00:00Z', 'ir': 19},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-29T00:00:00Z', 'ir': 64},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-30T00:00:00Z', 'ir': 42},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-05-31T00:00:00Z', 'ir': 15},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-01T00:00:00Z', 'ir': 54},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-02T00:00:00Z', 'ir': 68},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-03T00:00:00Z', 'ir': 17},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-04T00:00:00Z', 'ir': 14},
 {'aid': 336834650, 'cc': 'VN', 'd': '2015-06-05T00:00:00Z', 'ir': 23},

In [26]:
# group the data by app id and unified id

df_perf = pd.DataFrame(app_performance_data)

In [29]:
df_perf

,aid,cc,d,ir,au,iu,ar,c,u,r,aid_str
0,336834650,VN,2014-01-13T00:00:00Z,8,NaN,NaN,NaN,NaN,NaN,NaN,336834650
1,336834650,VN,2014-01-17T00:00:00Z,4,NaN,NaN,NaN,NaN,NaN,NaN,336834650
2,336834650,VN,2014-01-19T00:00:00Z,6,NaN,NaN,NaN,NaN,NaN,NaN,336834650
3,336834650,VN,2014-01-22T00:00:00Z,NaN,NaN,NaN,NaN,NaN,NaN,NaN,336834650
4,336834650,VN,2014-01-28T00:00:00Z,1,NaN,NaN,NaN,NaN,NaN,NaN,336834650
...,...,...,...,...,...,...,...,...,...,...,...
52747274,world.playme.x,NaN,2025-10-20T00:00:00Z,NaN,NaN,NaN,NaN,VN,NaN,68,world.playme.x
52747275,world.playme.x,NaN,2025-10-21T00:00:00Z,NaN,NaN,NaN,NaN,VN,NaN,81,world.playme.x
52747276,world.playme.x,NaN,2025-10-22T00:00:00Z,NaN,NaN,NaN,NaN,VN,NaN,NaN,world.playme.x
52747277,world.playme.x,NaN,2025-10-23T00:00:00Z,NaN,NaN,NaN,NaN,VN,NaN,NaN,world.playme.x
52747278,world.playme.x,NaN,2025-10-24T00:00:00Z,NaN,NaN,NaN,NaN,VN,NaN,NaN,world.playme.x

In [28]:
# Make sure app ids are consistent types (strings in this example)
df_perf["aid_str"] = df_perf["aid"].astype(str)

In [30]:
df_perf["d"] = pd.to_datetime(df_perf["d"])

In [31]:
# Make a string version of app_id too
df_app_full_info["app_id_str"] = df_app_full_info["app_id"].astype(str)

In [34]:
# Convert app id list to strings
list_app_ids_ios_str = [str(a) for a in list_app_ids_ios]
list_app_ids_android_str = [str(a) for a in list_app_ids_android]

In [36]:
list_app_ids_str = list_app_ids_ios_str + list_app_ids_android

In [35]:
# Keep only rows for those app IDs
df_app_ios_info = df_app_full_info[
    df_app_full_info["app_id_str"].isin(list_app_ids_ios_str)
]
df_app_android_info = df_app_full_info[
    df_app_full_info["app_id_str"].isin(list_app_ids_android_str)
]

In [39]:
# Sort by app and date (equivalent to your per-app sorted(..., key=lambda x["d"]))
df_perf = df_perf.sort_values(["aid_str", "d"])

In [ ]:
# For each app, get a list of dicts (one dict per performance row)
perf_lists = (
    df_perf
    .groupby("aid_str", sort=False)
    .apply(lambda g: g.to_dict("records"))
)